const COFFEES = [
  {
    id: 1,
    name: "Espresso",
    nameZh: "浓缩咖啡",
    category: "espresso",
    ingredients: ["7-9g 咖啡粉", "25-30ml 热水"],
    method: "espresso machine",
    flavor: ["浓郁", "苦甜", "焦糖"],
    strength: "strong",
    caffeine: "high",
    desc: "Espresso是所有意式咖啡的灵魂基底，起源于20世纪初的意大利。高压热水在25-30秒内穿过细研磨咖啡粉，萃取出一杯仅25-30ml的浓缩精华。表面金黄色的Crema油脂层是品质的标志，香气浓郁、口感醇厚。",
    tips: "品鉴时先观察Crema的颜色和厚度，闻香后小口啜饮，让咖啡在口腔中充分展开风味。",
    color: "#3e1f0d"
  },
  {
    id: 2,
    name: "Doppio",
    nameZh: "双份浓缩",
    category: "espresso",
    ingredients: ["14-18g 咖啡粉", "50-60ml 热水"],
    method: "espresso machine",
    flavor: ["浓烈", "饱满", "巧克力"],
    strength: "strong",
    caffeine: "high",
    desc: "Doppio在意大利语中意为'双倍'，是标准Espresso的两倍用量。它提供了更为浓郁饱满的咖啡体验，适合喜欢强烈口感的咖啡爱好者。在许多精品咖啡馆中，Doppio已成为默认的浓缩标准。",
    tips: "Doppio的咖啡因含量较高，建议在上午饮用，避免影响睡眠质量。",
    color: "#2d1508"
  },
  {
    id: 3,
    name: "Ristretto",
    nameZh: "短萃浓缩",
    category: "espresso",
    ingredients: ["7-9g 咖啡粉", "15-20ml 热水"],
    method: "espresso machine",
    flavor: ["甜感", "浓稠", "果香"],
    strength: "strong",
    caffeine: "medium",
    desc: "Ristretto是比Espresso更短的萃取，使用相同的咖啡粉量但只用一半的水量。由于萃取时间更短，苦味物质来不及被提取，因此口感更加甜美浓稠。它被认为是浓缩咖啡中最精华的部分。",
    tips: "Ristretto萃取时间约为15-18秒，比标准Espresso短，注意观察出液颜色变化来判断萃取状态。",
    color: "#4a2010"
  },
  {
    id: 4,
    name: "Lungo",
    nameZh: "长萃咖啡",
    category: "espresso",
    ingredients: ["7-9g 咖啡粉", "50-60ml 热水"],
    method: "espresso machine",
    flavor: ["微苦", "轻盈", "烟熏"],
    strength: "medium",
    caffeine: "high",
    desc: "Lungo在意大利语中意为'长'，萃取时间比标准Espresso更长，使用更多的水。这种方式会提取出更多的风味物质，口感比Espresso更轻柔但也略带苦味。它是介于浓缩和美式之间的平衡选择。",
    tips: "Lungo的萃取时间约为45-60秒，不宜过长，否则会产生过度萃取的焦苦味。",
    color: "#5a3018"
  },
  {
    id: 5,
    name: "Americano",
    nameZh: "美式咖啡",
    category: "espresso",
    ingredients: ["30ml 浓缩咖啡", "200ml 热水"],
    method: "espresso machine",
    flavor: ["清爽", "微苦", "顺滑"],
    strength: "medium",
    caffeine: "high",
    desc: "美式咖啡据说起源于二战时期驻扎在意大利的美国士兵，他们觉得Espresso太浓，于是加热水稀释饮用。这种简单的做法保留了浓缩的香气和风味，同时口感更加温和易饮，是全球最受欢迎的咖啡之一。",
    tips: "先倒热水再加浓缩，可以更好地保留Crema油脂层，获得更佳的视觉和口感体验。",
    color: "#6b3a1f"
  },
  {
    id: 6,
    name: "Red Eye",
    nameZh: "红眼咖啡",
    category: "espresso",
    ingredients: ["30ml 浓缩咖啡", "240ml 滴滤咖啡"],
    method: "espresso machine",
    flavor: ["强劲", "苦烈", "醒神"],
    strength: "strong",
    caffeine: "high",
    desc: "红眼咖啡是将一份Espresso加入一杯普通滴滤咖啡中，咖啡因含量极高。其名称来源于通宵飞行'红眼航班'的旅客，他们需要这种超强咖啡来保持清醒。它是咖啡因爱好者的终极选择。",
    tips: "红眼咖啡的咖啡因含量约为普通咖啡的两倍，不建议在下午三点后饮用，心脏敏感人群请谨慎。",
    color: "#4d2812"
  },
  {
    id: 7,
    name: "Latte",
    nameZh: "拿铁",
    category: "milk",
    ingredients: ["30ml 浓缩咖啡", "200ml 蒸汽牛奶", "少量奶泡"],
    method: "espresso machine",
    flavor: ["奶香", "柔滑", "甜润"],
    strength: "light",
    caffeine: "medium",
    desc: "拿铁是意大利语'牛奶'的意思，由浓缩咖啡与大量蒸汽牛奶混合而成。它是世界上最受欢迎的咖啡饮品之一，温和的口感让不习惯纯黑咖啡的人也能享受咖啡的美好。拿铁也是拉花艺术的最佳载体。",
    tips: "打奶泡时牛奶温度控制在60-65°C为最佳，过高会破坏牛奶的天然甜味和顺滑口感。",
    color: "#c4956a"
  },
  {
    id: 8,
    name: "Cappuccino",
    nameZh: "卡布奇诺",
    category: "milk",
    ingredients: ["30ml 浓缩咖啡", "120ml 蒸汽牛奶", "120ml 厚奶泡"],
    method: "espresso machine",
    flavor: ["奶泡绵密", "平衡", "微甜"],
    strength: "medium",
    caffeine: "medium",
    desc: "卡布奇诺得名于意大利卡普钦修道士的棕色头巾，传统比例为三等分的浓缩、蒸汽牛奶和奶泡。其标志性的厚密奶泡是灵魂所在，在意大利传统中只在早晨饮用。绵密的口感和浓郁的咖啡香完美交融。",
    tips: "传统卡布奇诺的体积不应超过180ml，奶泡厚度约1-1.5厘米，在上面撒少许可可粉更添风味。",
    color: "#b07d55"
  },
  {
    id: 9,
    name: "Flat White",
    nameZh: "馥芮白",
    category: "milk",
    ingredients: ["60ml 双份浓缩", "120ml 微泡牛奶"],
    method: "espresso machine",
    flavor: ["咖啡感强", "丝滑", "奶甜"],
    strength: "medium",
    caffeine: "high",
    desc: "Flat White起源于澳大利亚和新西兰，与拿铁相比使用更多的浓缩咖啡和更少的牛奶。其最大特点是使用极细腻的微泡牛奶，几乎看不到明显的泡沫层，咖啡与牛奶的融合更加紧密，咖啡风味更加突出。",
    tips: "Flat White的关键在于微泡奶的质地，像液态丝绸般细腻光滑，蒸汽棒应插入更深的位置来减少注入空气量。",
    color: "#a8825c"
  },
  {
    id: 10,
    name: "Cortado",
    nameZh: "科尔塔多",
    category: "milk",
    ingredients: ["30ml 浓缩咖啡", "30ml 温热牛奶"],
    method: "espresso machine",
    flavor: ["均衡", "醇厚", "微甜"],
    strength: "medium",
    caffeine: "medium",
    desc: "Cortado源自西班牙，名称来自西班牙语'cortar'意为'切割'，指用少量牛奶来'切割'浓缩咖啡的强烈苦味。它的牛奶与咖啡比例为1:1，是最为均衡的咖啡牛奶饮品之一，非常适合在午后慢慢品味。",
    tips: "Cortado通常使用小型玻璃杯盛装，牛奶只需微温即可，不需要打出厚奶泡。",
    color: "#9a7450"
  },
  {
    id: 11,
    name: "Macchiato",
    nameZh: "玛奇朵",
    category: "milk",
    ingredients: ["30ml 浓缩咖啡", "一勺奶泡"],
    method: "espresso machine",
    flavor: ["浓郁", "奶香点缀", "强烈"],
    strength: "strong",
    caffeine: "medium",
    desc: "Macchiato在意大利语中意为'被标记的'，是在浓缩咖啡上点缀一小勺奶泡。这种做法既保留了Espresso的强烈个性，又用一抹奶香温柔了锋利的苦味。传统Macchiato只有小小一杯，是意大利人午后的经典选择。",
    tips: "请注意传统意式Macchiato与美式连锁店的焦糖玛奇朵是完全不同的饮品，点单时需确认。",
    color: "#5c3620"
  },
  {
    id: 12,
    name: "Mocha",
    nameZh: "摩卡",
    category: "milk",
    ingredients: ["30ml 浓缩咖啡", "30ml 巧克力酱", "150ml 蒸汽牛奶", "鲜奶油"],
    method: "espresso machine",
    flavor: ["巧克力", "香甜", "浓滑"],
    strength: "light",
    caffeine: "medium",
    desc: "摩卡咖啡融合了浓缩咖啡、巧克力和牛奶三种风味，得名于也门的摩卡港——历史上重要的咖啡贸易港口。这款饮品甜蜜浓郁，是咖啡与可可的完美联姻，很适合作为甜品般的咖啡享受。",
    tips: "使用优质黑巧克力酱代替糖浆，会让摩卡的层次感更丰富，也可以在顶部撒些可可粉或肉桂粉。",
    color: "#5e3a22"
  },
  {
    id: 13,
    name: "Dirty",
    nameZh: "脏咖啡",
    category: "milk",
    ingredients: ["30ml 浓缩咖啡", "150ml 冰牛奶"],
    method: "espresso machine",
    flavor: ["冰爽", "层次分明", "先苦后甜"],
    strength: "medium",
    caffeine: "medium",
    desc: "脏咖啡因其'脏兮兮'的外观而得名：将浓缩咖啡直接倒在冰牛奶表面，形成美丽的渐变层次。咖啡与牛奶不预先混合，饮用时从浓到淡，体验风味的自然过渡。这是近年来风靡亚洲咖啡界的网红饮品。",
    tips: "制作时杯中先放冰块和冷牛奶，浓缩咖啡沿杯壁缓缓倒入，保持分层效果，拍照后尽快饮用。",
    color: "#8b6e52"
  },
  {
    id: 14,
    name: "Piccolo",
    nameZh: "短笛拿铁",
    category: "milk",
    ingredients: ["20ml Ristretto浓缩", "60ml 蒸汽牛奶"],
    method: "espresso machine",
    flavor: ["精致", "奶甜", "咖啡香突出"],
    strength: "medium",
    caffeine: "low",
    desc: "Piccolo在意大利语中意为'小'，是一杯迷你版的拿铁。它使用Ristretto短萃作为基底，配以少量精心打发的微泡牛奶，通常盛装在小型拿铁杯或玻璃杯中。虽然体积小巧，但风味浓缩、层次丰富。",
    tips: "Piccolo适合在一天中多次品饮，既能满足对咖啡的渴望，又不会因摄入过多牛奶或咖啡因而负担过重。",
    color: "#b8956d"
  },
  {
    id: 15,
    name: "Breve",
    nameZh: "布蕾咖啡",
    category: "milk",
    ingredients: ["30ml 浓缩咖啡", "120ml 半对半奶油", "奶泡"],
    method: "espresso machine",
    flavor: ["奶油感", "香浓", "甜腻"],
    strength: "medium",
    caffeine: "medium",
    desc: "Breve是美式风格的拿铁变体，用半对半奶油（Half & Half）代替普通牛奶。由于奶油脂肪含量更高，打出的奶泡更加绵密厚实，口感极为醇厚丝滑。它是美国咖啡文化中独特的创造，特别受甜食爱好者欢迎。",
    tips: "由于半对半奶油热量较高，可以选择小杯饮用，或者用它作为偶尔的特别犒赏。",
    color: "#d4b896"
  },
  {
    id: 16,
    name: "Vienna Coffee",
    nameZh: "维也纳咖啡",
    category: "milk",
    ingredients: ["60ml 双份浓缩", "大量鲜奶油", "巧克力碎"],
    method: "espresso machine",
    flavor: ["奶油香", "甜蜜", "优雅"],
    strength: "medium",
    caffeine: "high",
    desc: "维也纳咖啡是奥地利咖啡文化的代表，在浓郁的黑咖啡上覆盖厚厚一层手打鲜奶油。维也纳的咖啡馆文化已被列入联合国非物质文化遗产，人们在古典优雅的咖啡馆中品味这杯经典，是一种生活艺术的享受。",
    tips: "正宗的维也纳咖啡不应搅拌，要透过冰凉的鲜奶油啜饮热咖啡，感受冷热交融的美妙体验。",
    color: "#f5e6d3"
  },
  {
    id: 17,
    name: "Cold Brew",
    nameZh: "冷萃咖啡",
    category: "cold",
    ingredients: ["80g 粗研磨咖啡粉", "1000ml 冷水"],
    method: "cold brew",
    flavor: ["清爽", "低酸", "甘甜"],
    strength: "medium",
    caffeine: "high",
    desc: "冷萃咖啡使用冷水长时间浸泡咖啡粉，通常需要12-24小时。低温慢萃的方式大幅降低了酸度和苦味，带来格外顺滑甘甜的口感。它是夏日最受欢迎的咖啡饮品之一，也是精品咖啡馆的常驻菜单。",
    tips: "咖啡粉与水的比例建议为1:12至1:15，浸泡后用滤纸过滤，冷藏可保存3-5天。",
    color: "#4a3020"
  },
  {
    id: 18,
    name: "Iced Latte",
    nameZh: "冰拿铁",
    category: "cold",
    ingredients: ["60ml 双份浓缩", "200ml 冰牛奶", "冰块"],
    method: "espresso machine",
    flavor: ["冰爽", "奶香", "清新"],
    strength: "light",
    caffeine: "high",
    desc: "冰拿铁将浓缩咖啡与冰牛奶和冰块结合，是夏季咖啡饮品的绝对王者。清凉的口感配上牛奶的柔和与咖啡的醇香，令人精神为之一振。在全球各大咖啡连锁店中，冰拿铁常年稳居销量榜首。",
    tips: "可以先将浓缩咖啡冷却或直接倒在冰块上快速降温，避免冰块快速融化稀释口感。",
    color: "#c9a882"
  },
  {
    id: 19,
    name: "Affogato",
    nameZh: "阿芙佳朵",
    category: "cold",
    ingredients: ["30ml 浓缩咖啡", "一球香草冰淇淋"],
    method: "espresso machine",
    flavor: ["甜蜜", "冷热交融", "香草"],
    strength: "medium",
    caffeine: "medium",
    desc: "Affogato在意大利语中意为'淹没'，将一份热浓缩咖啡浇淋在冰淇淋上。冰淇淋在热咖啡中缓缓融化，创造出冷热、甜苦、柔滑与浓烈的多重对比。它既是咖啡也是甜点，是意大利餐后的经典收尾。",
    tips: "浓缩咖啡必须趁热浇在冰淇淋上并立即享用，选用高品质香草冰淇淋会让体验大大升级。",
    color: "#f0dfc3"
  },
  {
    id: 20,
    name: "Espresso Tonic",
    nameZh: "咖啡汤力",
    category: "cold",
    ingredients: ["30ml 浓缩咖啡", "150ml 汤力水", "冰块", "柠檬片"],
    method: "espresso machine",
    flavor: ["气泡感", "苦甜交织", "清凉"],
    strength: "light",
    caffeine: "medium",
    desc: "咖啡汤力是近年精品咖啡界的创意之作，将浓缩咖啡与汤力水碰撞出意想不到的火花。汤力水的气泡和奎宁苦味与咖啡的焦苦形成奇妙的互补，加入冰块和柠檬后，是一杯充满活力的夏日特饮。",
    tips: "先在杯中放入冰块和汤力水，再沿冰块缓缓倒入浓缩咖啡，可以看到美丽的渐变分层效果。",
    color: "#c8a060"
  },
  {
    id: 21,
    name: "Frappuccino-style Blended",
    nameZh: "冰沙咖啡",
    category: "cold",
    ingredients: ["60ml 浓缩咖啡", "150ml 牛奶", "冰块", "糖浆", "鲜奶油"],
    method: "espresso machine",
    flavor: ["冰沙质地", "香甜", "奶油"],
    strength: "light",
    caffeine: "medium",
    desc: "冰沙咖啡将浓缩咖啡、牛奶、冰块和糖浆一起搅打成冰沙状，是风靡全球的冰饮咖啡品类。绵密的冰沙口感配上顶部的鲜奶油，既是解暑良品也是甜蜜享受。它让不常喝咖啡的人也能轻松接受咖啡的味道。",
    tips: "搅打时间不宜过长，保持一定的冰沙颗粒感比完全打碎口感更好，可以加入各种调味糖浆创造新口味。",
    color: "#d9c4a8"
  },
  {
    id: 22,
    name: "Shakerato",
    nameZh: "摇摇冰咖啡",
    category: "cold",
    ingredients: ["60ml 双份浓缩", "10g 砂糖", "冰块"],
    method: "espresso machine",
    flavor: ["冰爽", "绵密泡沫", "焦糖甜"],
    strength: "medium",
    caffeine: "high",
    desc: "Shakerato是意大利夏日的经典冰咖啡，将新鲜萃取的浓缩咖啡和糖与冰块一起在摇酒器中大力摇晃。剧烈的摇晃产生了丰富细腻的泡沫，口感冰凉绵密。倒入鸡尾酒杯中，优雅而令人愉悦。",
    tips: "使用调酒摇壶(Shaker)大力摇晃约15秒，滤去冰块后倒入冰镇的马天尼杯中享用效果最佳。",
    color: "#7a5535"
  },
  {
    id: 23,
    name: "V60 Hand Drip",
    nameZh: "V60手冲咖啡",
    category: "specialty",
    ingredients: ["15-18g 中细研磨咖啡粉", "250-300ml 热水(90-96°C)"],
    method: "pour over",
    flavor: ["明亮", "花果香", "干净"],
    strength: "light",
    caffeine: "medium",
    desc: "V60是由日本Hario公司设计的锥形滤杯，60度角的造型和螺旋沟纹设计使其成为手冲咖啡的经典代表。V60冲煮强调水流控制和注水手法，能够清晰呈现咖啡豆的产地风味特征，是精品咖啡爱好者的入门首选。",
    tips: "先用少量热水润湿滤纸去除纸味，注水时采用中心向外的螺旋方式，闷蒸30秒后开始正式注水。",
    color: "#9c6b40"
  },
  {
    id: 24,
    name: "Chemex",
    nameZh: "Chemex手冲壶",
    category: "specialty",
    ingredients: ["25-30g 中粗研磨咖啡粉", "400-450ml 热水(92-96°C)"],
    method: "pour over",
    flavor: ["清透", "明亮", "茶感"],
    strength: "light",
    caffeine: "medium",
    desc: "Chemex诞生于1941年，由德国化学家Peter Schlumbohm发明，其优雅的沙漏造型是现代设计经典，被纽约现代艺术博物馆永久收藏。Chemex使用比普通滤纸厚20-30%的专用滤纸，过滤出极其干净清透的咖啡液体。",
    tips: "Chemex的较厚滤纸会减慢流速，研磨度应比V60略粗，注水速度也需适当放慢以控制总萃取时间在4-5分钟。",
    color: "#a87845"
  },
  {
    id: 25,
    name: "French Press",
    nameZh: "法压壶咖啡",
    category: "specialty",
    ingredients: ["18g 粗研磨咖啡粉", "300ml 热水(93-96°C)"],
    method: "french press",
    flavor: ["醇厚", "油脂感", "饱满"],
    strength: "medium",
    caffeine: "medium",
    desc: "法压壶是最简单直接的咖啡冲泡方式之一，通过浸泡而非滴滤来萃取。由于金属滤网不会过滤掉咖啡油脂，因此口感特别醇厚饱满。法压壶于1929年在意大利获得专利，后在法国流行开来，是家庭咖啡冲泡的经典之选。",
    tips: "浸泡4分钟后缓慢压下滤网，压到底后立即倒出咖啡，避免过度萃取导致苦涩。",
    color: "#7d5530"
  },
  {
    id: 26,
    name: "AeroPress",
    nameZh: "爱乐压咖啡",
    category: "specialty",
    ingredients: ["15-18g 中细研磨咖啡粉", "200ml 热水(80-96°C)"],
    method: "aeropress",
    flavor: ["顺滑", "干净", "多变"],
    strength: "medium",
    caffeine: "medium",
    desc: "爱乐压由飞盘发明者Alan Adler于2005年发明，利用气压原理快速萃取咖啡。它体积小巧、便于携带，冲泡方式灵活多变。每年世界各地举办AeroPress锦标赛，选手们用各种创意配方展现这款器具的无限可能。",
    tips: "尝试反转法(Inverted Method)：将爱乐压倒置注水浸泡后翻转压出，可以获得更浓郁的风味。",
    color: "#8a6038"
  },
  {
    id: 27,
    name: "Moka Pot",
    nameZh: "摩卡壶咖啡",
    category: "specialty",
    ingredients: ["15-20g 中细研磨咖啡粉", "下壶注满热水"],
    method: "moka pot",
    flavor: ["浓烈", "金属感", "烟熏"],
    strength: "strong",
    caffeine: "high",
    desc: "摩卡壶由意大利人Alfonso Bialetti于1933年发明，利用蒸汽压力将水推过咖啡粉层。它是意大利家庭的标配厨具，几乎每个意大利家庭都拥有一把。经典的八角形Bialetti摩卡壶已成为意大利设计的文化符号。",
    tips: "下壶使用预先加热的水可以避免咖啡粉在加热过程中被烤焦，听到咕噜声响时立即关火并用冷毛巾降温。",
    color: "#4d3018"
  },
  {
    id: 28,
    name: "Siphon Coffee",
    nameZh: "虹吸壶咖啡",
    category: "specialty",
    ingredients: ["20g 中研磨咖啡粉", "300ml 热水"],
    method: "siphon",
    flavor: ["清澈", "细腻", "茶韵"],
    strength: "light",
    caffeine: "medium",
    desc: "虹吸壶利用真空原理冲煮咖啡，整个过程如同化学实验般充满观赏性。水在下壶加热后上升到上壶与咖啡粉接触，关火后咖啡液被真空吸回下壶。这种古老的冲煮方式在日本咖啡文化中占有重要地位。",
    tips: "萃取时间控制在60-90秒为宜，用竹搅棒以十字形搅拌咖啡粉，使其均匀浸湿。",
    color: "#a07850"
  },
  {
    id: 29,
    name: "Turkish Coffee",
    nameZh: "土耳其咖啡",
    category: "specialty",
    ingredients: ["7g 极细研磨咖啡粉", "65ml 冷水", "适量砂糖"],
    method: "siphon",
    flavor: ["浓稠", "香料感", "甘苦"],
    strength: "strong",
    caffeine: "high",
    desc: "土耳其咖啡拥有近500年的历史，是世界上最古老的咖啡冲煮方式之一。将极细研磨的咖啡粉与水和糖一起放在特制铜壶(Cezve)中加热至起泡。土耳其咖啡文化于2013年被列入联合国非物质文化遗产名录。",
    tips: "加热至泡沫升起时离火，重复2-3次，倒入杯中后静待咖啡渣沉淀再饮用，杯底的咖啡渣可用于占卜。",
    color: "#3a2010"
  },
  {
    id: 30,
    name: "Vietnamese Coffee",
    nameZh: "越南滴漏咖啡",
    category: "specialty",
    ingredients: ["25g 深烘咖啡粉", "炼乳适量", "热水适量"],
    method: "pour over",
    flavor: ["甜腻", "浓郁", "焦糖"],
    strength: "strong",
    caffeine: "high",
    desc: "越南滴漏咖啡使用特有的金属滴漏壶(Phin)冲泡，搭配香甜的炼乳饮用。法国殖民时期将咖啡文化带入越南，越南人创造性地用炼乳替代鲜奶，形成了独特的咖啡传统。如今越南是全球第二大咖啡生产国。",
    tips: "先在杯底加入两勺炼乳，再将Phin壶放在杯上缓慢滴滤，喝冰的版本只需加入大量冰块搅拌即可。",
    color: "#5c3a1a"
  },
  {
    id: 31,
    name: "Ethiopian Yirgacheffe",
    nameZh: "埃塞俄比亚耶加雪菲",
    category: "origin",
    ingredients: ["15g 中研磨咖啡粉", "250ml 热水(90-93°C)"],
    method: "pour over",
    flavor: ["柑橘", "茉莉花", "蜂蜜", "明亮酸质"],
    strength: "light",
    caffeine: "medium",
    desc: "耶加雪菲产自咖啡发源地埃塞俄比亚南部，海拔1700-2200米的高原地带。这里被认为是咖啡最初的故乡，至今仍保留着野生咖啡树林。耶加雪菲以其明亮的花果香气闻名于世，被誉为咖啡中的'香水'。",
    tips: "建议使用浅中烘焙豆，手冲方式最能展现其精致的花香和柑橘风味，水温不宜超过93°C。",
    color: "#c49560"
  },
  {
    id: 32,
    name: "Colombian Supremo",
    nameZh: "哥伦比亚特级",
    category: "origin",
    ingredients: ["15g 中研磨咖啡粉", "250ml 热水(92-95°C)"],
    method: "pour over",
    flavor: ["坚果", "焦糖", "红果", "均衡"],
    strength: "medium",
    caffeine: "medium",
    desc: "哥伦比亚是全球第三大咖啡生产国，Supremo是其最高等级的咖啡豆分类。生长在安第斯山脉1200-1800米的理想海拔区间，火山土壤赋予了咖啡丰富的矿物质。其口感平衡醇和，是各种冲泡方式都适宜的万能豆。",
    tips: "哥伦比亚豆适合中度烘焙，无论手冲、法压还是意式都能表现出色，是入门精品咖啡的绝佳选择。",
    color: "#8b6040"
  },
  {
    id: 33,
    name: "Kenyan AA",
    nameZh: "肯尼亚AA",
    category: "origin",
    ingredients: ["15g 中研磨咖啡粉", "250ml 热水(92-95°C)"],
    method: "pour over",
    flavor: ["黑加仑", "番茄酸", "莓果", "饱满酒体"],
    strength: "medium",
    caffeine: "medium",
    desc: "肯尼亚AA代表咖啡豆最大颗粒等级，产自肯尼亚中部高原的火山红土地带。独特的双重发酵水洗处理法赋予其标志性的明亮酸质和果汁般的口感。肯尼亚咖啡在精品咖啡界享有极高声誉，常在国际杯测竞赛中获奖。",
    tips: "肯尼亚AA的酸质非常明亮活泼，建议浅至中烘焙以充分展现其水果风味，搭配甜点饮用可以平衡酸度。",
    color: "#a07048"
  },
  {
    id: 34,
    name: "Guatemalan Antigua",
    nameZh: "危地马拉安提瓜",
    category: "origin",
    ingredients: ["15g 中研磨咖啡粉", "250ml 热水(92-95°C)"],
    method: "pour over",
    flavor: ["可可", "烟熏", "香料", "丝滑"],
    strength: "medium",
    caffeine: "medium",
    desc: "安提瓜产区位于危地马拉三座火山之间的山谷中，海拔1500米以上，拥有得天独厚的微气候条件。火山灰富含矿物质的土壤滋养出风味复杂多层次的咖啡豆。安提瓜咖啡以浓郁的可可韵味和丝滑口感著称于世。",
    tips: "安提瓜咖啡适合中深烘焙，能很好地平衡甜感和醇厚度，用法压壶冲泡可以充分展现其饱满的体质感。",
    color: "#6d4830"
  },
  {
    id: 35,
    name: "Jamaican Blue Mountain",
    nameZh: "牙买加蓝山咖啡",
    category: "origin",
    ingredients: ["15g 中研磨咖啡粉", "250ml 热水(90-93°C)"],
    method: "pour over",
    flavor: ["柔和", "花香", "坚果", "完美平衡"],
    strength: "light",
    caffeine: "medium",
    desc: "蓝山咖啡产自牙买加蓝山山脉海拔900-1700米的狭小产区，年产量极为有限。它被誉为'咖啡中的劳斯莱斯'，以无可挑剔的平衡感著称——酸、甜、苦三者达到了近乎完美的和谐。日本进口了蓝山咖啡约80%的产量。",
    tips: "蓝山咖啡风味精致微妙，建议用中浅烘焙搭配手冲冲泡，避免加糖加奶，以纯粹品味其罕见的平衡之美。",
    color: "#b8956a"
  },
  {
    id: 36,
    name: "Panama Geisha",
    nameZh: "巴拿马瑰夏",
    category: "origin",
    ingredients: ["15g 中研磨咖啡粉", "250ml 热水(90-92°C)"],
    method: "pour over",
    flavor: ["茉莉", "佛手柑", "热带水果", "蜜糖"],
    strength: "light",
    caffeine: "medium",
    desc: "瑰夏(Geisha)品种原产于埃塞俄比亚瑰夏山，在巴拿马翡翠庄园种植后于2004年一鸣惊人，以破纪录的价格震惊咖啡界。其花香和水果风味的强度前所未有，被誉为'上帝的调色板'。至今仍是精品咖啡拍卖会上最昂贵的咖啡品种。",
    tips: "瑰夏咖啡价格高昂，冲泡时务必精准控制参数：水温90°C、研磨偏细、注水缓慢，以最大化呈现其华丽风味。",
    color: "#d4a868"
  },
  {
    id: 37,
    name: "Espresso Romano",
    nameZh: "罗马浓缩",
    category: "espresso",
    ingredients: ["30ml 浓缩咖啡", "一片柠檬皮"],
    method: "espresso machine",
    flavor: ["柑橘", "清爽", "酸甜"],
    strength: "strong",
    caffeine: "medium",
    desc: "罗马浓缩是在标准Espresso旁配一片柠檬皮，饮用前用柠檬皮在杯沿擦一圈。柠檬的清香与咖啡的浓郁相得益彰，据说这种喝法可以增强味觉感受。虽然名为'罗马'，但在罗马当地并不常见，更多流行于美国。",
    tips: "只需用柠檬皮轻轻擦拭杯沿即可，不要将柠檬汁挤入咖啡中，以免酸度过重掩盖咖啡风味。",
    color: "#5a3520"
  },
  {
    id: 38,
    name: "Espresso Con Panna",
    nameZh: "康宝蓝",
    category: "espresso",
    ingredients: ["30ml 浓缩咖啡", "一团鲜奶油"],
    method: "espresso machine",
    flavor: ["奶油甜", "浓郁", "柔和"],
    strength: "strong",
    caffeine: "medium",
    desc: "康宝蓝在意大利语中意为'加奶油的浓缩咖啡'，是在一杯Espresso上点缀一团手打鲜奶油。看似简单的组合却创造出美妙的味觉层次：先是冰凉甜美的奶油，接着是滚烫浓烈的咖啡，冷热甜苦的对比令人难忘。",
    tips: "鲜奶油应手工打发至六七分硬度，用勺子轻轻放在咖啡上方，不要搅拌，直接啜饮即可。",
    color: "#f2e0c8"
  },
  {
    id: 39,
    name: "Irish Coffee",
    nameZh: "爱尔兰咖啡",
    category: "espresso",
    ingredients: ["60ml 热咖啡", "40ml 爱尔兰威士忌", "15g 红糖", "鲜奶油"],
    method: "espresso machine",
    flavor: ["威士忌香", "温暖", "甜蜜醇厚"],
    strength: "medium",
    caffeine: "medium",
    desc: "爱尔兰咖啡诞生于1940年代的爱尔兰香农机场，调酒师Joe Sheridan为寒冷中等待航班的旅客发明了这款温暖身心的饮品。它是咖啡与鸡尾酒的完美跨界，热咖啡的醇香与威士忌的温润交织，顶层鲜奶油如丝般柔滑。",
    tips: "必须使用专用的爱尔兰咖啡杯，先将杯子用热水预热，鲜奶油要沿勺背缓缓浮在咖啡表面不搅拌。",
    color: "#7a5535"
  },
  {
    id: 40,
    name: "Café Bombón",
    nameZh: "蜜糖咖啡",
    category: "espresso",
    ingredients: ["30ml 浓缩咖啡", "30ml 炼乳"],
    method: "espresso machine",
    flavor: ["极甜", "浓稠", "焦糖奶香"],
    strength: "medium",
    caffeine: "medium",
    desc: "蜜糖咖啡源自西班牙瓦伦西亚地区，将浓缩咖啡与等量炼乳层叠在透明玻璃杯中。深褐色的咖啡与乳白色的炼乳形成鲜明的双色分层，视觉效果令人惊艳。这款饮品在东南亚也极受欢迎，是甜味咖啡爱好者的至爱。",
    tips: "使用透明玻璃杯可以欣赏美丽的分层效果，先倒入炼乳再缓缓加入浓缩咖啡，饮用前可搅拌混合。",
    color: "#c49060"
  }
];

const COFFEE_CATEGORY_LABELS = {espresso:"意式浓缩",milk:"牛奶咖啡",black:"黑咖啡",cold:"冷饮",specialty:"手冲/器具",origin:"精品产地"};
const COFFEE_CATEGORY_EMOJI = {espresso:"☕",milk:"🥛",black:"🫗",cold:"🧊",specialty:"⚗️",origin:"🌍"};
