const EXERCISES = [
  {
    id: 1,
    name: "Back Squat",
    nameZh: "杠铃深蹲",
    category: "squat",
    equipment: "杠铃",
    muscles: "股四头肌、臀大肌、竖脊肌",
    difficulty: "intermediate",
    sets: "3-5组",
    reps: "5-8次",
    description: "将杠铃置于上背部斜方肌位置，双脚与肩同宽，屈髋屈膝下蹲至大腿平行或略低于地面，再站起。杠铃深蹲是下肢力量训练之王，能有效提升运动表现中的加速、跳跃和变向能力。长期训练可显著增强核心稳定性和整体力量输出。",
    tips: "下蹲时膝盖沿脚尖方向打开，保持胸椎挺直，避免骨盆后倾。",
    color: "#E74C3C"
  },
  {
    id: 2,
    name: "Front Squat",
    nameZh: "前蹲",
    category: "squat",
    equipment: "杠铃",
    muscles: "股四头肌、臀大肌、上背部",
    difficulty: "intermediate",
    sets: "3-4组",
    reps: "6-10次",
    description: "杠铃置于锁骨与三角肌前束之间，采用交叉握或前架位握法。前蹲要求更直立的躯干姿态，对股四头肌和上背部的刺激更强。该动作对于提升举重技术和运动中的制动能力非常有帮助。",
    tips: "保持手肘高抬，上臂平行于地面，防止杠铃前滑。",
    color: "#C0392B"
  },
  {
    id: 3,
    name: "Bulgarian Split Squat",
    nameZh: "保加利亚分腿蹲",
    category: "squat",
    equipment: "哑铃",
    muscles: "股四头肌、臀大肌、髋屈肌",
    difficulty: "intermediate",
    sets: "3-4组",
    reps: "8-12次/侧",
    description: "后脚抬高置于长凳上，前脚向前一大步，手持哑铃做单腿下蹲。该动作能有效改善左右腿力量不平衡，同时拉伸后腿髋屈肌。是跑步、球类运动等需要单腿发力场景的最佳辅助训练之一。",
    tips: "前膝不超过脚尖过多，躯干保持直立，重心落在前脚全掌。",
    color: "#E67E22"
  },
  {
    id: 4,
    name: "Goblet Squat",
    nameZh: "高脚杯深蹲",
    category: "squat",
    equipment: "壶铃",
    muscles: "股四头肌、臀大肌、核心",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "10-15次",
    description: "双手捧住壶铃或哑铃置于胸前，双脚略宽于肩站立，下蹲至最低位置。高脚杯深蹲是学习正确深蹲模式的最佳入门动作，前置负重自然引导直立的躯干姿态。适合初学者建立良好的下肢运动模式和基础力量。",
    tips: "下蹲底部用肘部轻推膝盖内侧向外，充分打开髋关节。",
    color: "#F39C12"
  },
  {
    id: 5,
    name: "Pistol Squat",
    nameZh: "单腿深蹲",
    category: "squat",
    equipment: "自重",
    muscles: "股四头肌、臀大肌、踝关节稳定肌",
    difficulty: "advanced",
    sets: "3-4组",
    reps: "3-6次/侧",
    description: "单腿站立，另一条腿向前伸直悬空，缓慢下蹲至最低点后站起。单腿深蹲是自重训练中最具挑战性的下肢动作，要求极高的单腿力量、平衡感和踝关节灵活性。掌握该动作意味着你拥有出色的功能性下肢能力。",
    tips: "初学者可手扶门框或使用弹力带辅助，逐步减少辅助量。",
    color: "#D35400"
  },
  {
    id: 6,
    name: "Push-up",
    nameZh: "俯卧撑",
    category: "push",
    equipment: "自重",
    muscles: "胸大肌、三角肌前束、肱三头肌",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "10-20次",
    description: "双手撑地略宽于肩，身体从头到脚保持一条直线，屈肘下降胸部接近地面后推起。俯卧撑是最经典的功能性推力训练，无需任何器械即可有效锻炼上肢推力链。同时对核心抗伸展稳定性有很好的训练效果。",
    tips: "全程收紧臀部和腹部，避免腰部塌陷或翘臀。",
    color: "#3498DB"
  },
  {
    id: 7,
    name: "Overhead Press",
    nameZh: "杠铃过头推举",
    category: "push",
    equipment: "杠铃",
    muscles: "三角肌、肱三头肌、上斜方肌",
    difficulty: "intermediate",
    sets: "3-5组",
    reps: "5-8次",
    description: "杠铃从锁骨前方起始，双手略宽于肩握杠，将杠铃垂直推举过头至手臂完全伸直。过头推举是衡量上肢推力力量的黄金标准动作，对肩关节稳定性和整体上肢力量的发展至关重要。运动员掌握这个动作能提升投掷、格斗等场景的表现。",
    tips: "推举时头部微微后收让杠铃通过，锁定后头部回到杠铃正下方。",
    color: "#2980B9"
  },
  {
    id: 8,
    name: "Bench Press",
    nameZh: "卧推",
    category: "push",
    equipment: "杠铃",
    muscles: "胸大肌、三角肌前束、肱三头肌",
    difficulty: "intermediate",
    sets: "3-5组",
    reps: "5-10次",
    description: "仰卧于卧推凳上，双手握杠铃下放至胸部中下端，停顿后推起至手臂伸直。卧推是上肢水平推力的基础训练，能显著提升推力方向的最大力量。对于需要推挡、格斗、橄榄球等推力需求的运动员尤为重要。",
    tips: "肩胛骨收紧下沉贴紧凳面，双脚踩实地面，建立稳定的力量传导链。",
    color: "#1ABC9C"
  },
  {
    id: 9,
    name: "Dips",
    nameZh: "双杠臂屈伸",
    category: "push",
    equipment: "双杠",
    muscles: "胸大肌下部、肱三头肌、三角肌前束",
    difficulty: "intermediate",
    sets: "3-4组",
    reps: "8-12次",
    description: "双手撑于平行双杠上，身体悬空，屈肘下降至上臂与地面平行后推起。双杠臂屈伸是一个优秀的上肢推力复合动作，可通过身体前倾角度调节胸肌和肱三头肌的参与比例。也是体操和街头健身的核心基础动作。",
    tips: "身体前倾约15-30度更多刺激胸肌，保持直立则侧重肱三头肌。",
    color: "#16A085"
  },
  {
    id: 10,
    name: "Pull-up",
    nameZh: "引体向上",
    category: "pull",
    equipment: "单杠",
    muscles: "背阔肌、肱二头肌、菱形肌",
    difficulty: "intermediate",
    sets: "3-5组",
    reps: "5-10次",
    description: "双手正握单杠略宽于肩，从完全悬垂位置拉起身体直到下巴超过杠面。引体向上是衡量相对力量的最佳指标之一，对攀爬、格斗抓握等运动场景至关重要。该动作高效发展整个后侧链的拉力能力。",
    tips: "起始时先下沉肩胛骨激活背部，避免纯靠手臂弯曲完成动作。",
    color: "#9B59B6"
  },
  {
    id: 11,
    name: "Barbell Row",
    nameZh: "杠铃划船",
    category: "pull",
    equipment: "杠铃",
    muscles: "背阔肌、菱形肌、后三角肌、肱二头肌",
    difficulty: "intermediate",
    sets: "3-4组",
    reps: "6-10次",
    description: "俯身约45度角，双手正握杠铃，将杠铃拉向下腹部，肩胛骨充分收缩后缓慢放下。杠铃划船是发展背部厚度和水平拉力的核心动作。强壮的划船能力直接转化为更好的体姿控制和运动中的拉扯对抗能力。",
    tips: "保持下背部自然弧度，避免借助躯干摆动发力。",
    color: "#8E44AD"
  },
  {
    id: 12,
    name: "Face Pull",
    nameZh: "面拉",
    category: "pull",
    equipment: "绳索",
    muscles: "后三角肌、菱形肌、外旋肌群",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "15-20次",
    description: "使用绳索附件设置于面部高度，双手握绳向面部拉动，同时外旋肩关节至手在耳朵两侧。面拉是维护肩关节健康最重要的辅助动作，能有效强化经常被忽视的后三角肌和肩外旋肌群。建议每次训练都包含该动作以平衡推拉比例。",
    tips: "拉到终点时挤压肩胛骨，想象两只手要碰到耳朵后方。",
    color: "#7D3C98"
  },
  {
    id: 13,
    name: "Deadlift",
    nameZh: "硬拉",
    category: "hinge",
    equipment: "杠铃",
    muscles: "竖脊肌、臀大肌、腘绳肌、斜方肌",
    difficulty: "intermediate",
    sets: "3-5组",
    reps: "3-6次",
    description: "双脚与髋同宽站立于杠铃后方，屈髋屈膝握住杠铃，通过伸髋伸膝将杠铃从地面拉起至完全站直。硬拉是人体能完成的最大负重动作之一，训练整个后侧链的协同发力。对于提升运动爆发力、抗伤害能力和整体力量水平有不可替代的作用。",
    tips: "杠铃紧贴身体上行，保持背部中立，起始发力先蹬地再伸髋。",
    color: "#2C3E50"
  },
  {
    id: 14,
    name: "Romanian Deadlift",
    nameZh: "罗马尼亚硬拉",
    category: "hinge",
    equipment: "杠铃",
    muscles: "腘绳肌、臀大肌、竖脊肌",
    difficulty: "intermediate",
    sets: "3-4组",
    reps: "8-12次",
    description: "站立位持杠铃，膝盖微屈，以髋关节为轴心将躯干前倾，杠铃沿大腿前侧下降至感到腘绳肌强烈拉伸后伸髋回起。罗马尼亚硬拉专注于髋铰链模式的离心控制，是发展腘绳肌力量和预防后侧链损伤的核心训练动作。",
    tips: "想象用臀部去碰身后的墙壁，保持杠铃紧贴大腿。",
    color: "#34495E"
  },
  {
    id: 15,
    name: "Kettlebell Swing",
    nameZh: "壶铃摆荡",
    category: "hinge",
    equipment: "壶铃",
    muscles: "臀大肌、腘绳肌、核心、前臂",
    difficulty: "beginner",
    sets: "3-5组",
    reps: "15-20次",
    description: "双手握壶铃站立，通过爆发性伸髋将壶铃摆至与肩同高，利用重力下落的惯性再次屈髋完成下一次摆动。壶铃摆荡是发展髋部爆发力和心肺耐力的高效动作，兼具力量训练和有氧训练的双重效果。短时间内即可达到极高的训练效率。",
    tips: "力量来源于髋部爆发而非手臂上拉，在最高点挤紧臀部。",
    color: "#E74C3C"
  },
  {
    id: 16,
    name: "Hip Thrust",
    nameZh: "臀推",
    category: "hinge",
    equipment: "杠铃",
    muscles: "臀大肌、腘绳肌",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "8-12次",
    description: "上背部靠在长凳边缘，杠铃放于髋部位置，双脚踩地与髋同宽，通过伸髋将杠铃顶起直到躯干与大腿平行。臀推是针对臀大肌最大化激活的动作，对提升冲刺速度、跳跃高度和髋伸展力量有直接帮助。很多运动员将其作为核心训练动作之一。",
    tips: "顶峰位置保持1-2秒挤压臀部，避免过度伸展腰椎。",
    color: "#A93226"
  },
  {
    id: 17,
    name: "Farmer's Walk",
    nameZh: "农夫行走",
    category: "carry",
    equipment: "哑铃",
    muscles: "斜方肌、前臂、核心、全身",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "30-40米",
    description: "双手各持一个重哑铃或专用农夫行走把手，保持挺胸收腹的姿态稳步行走规定距离。农夫行走是最具功能性的训练动作之一，同时训练握力、核心稳定性、肩部承载能力和整体体能。该动作模拟日常搬运重物的场景，实用性极强。",
    tips: "肩膀下沉远离耳朵，目视前方，步幅适中保持稳定。",
    color: "#27AE60"
  },
  {
    id: 18,
    name: "Waiter's Walk",
    nameZh: "服务员行走",
    category: "carry",
    equipment: "壶铃",
    muscles: "三角肌、核心抗侧屈肌群、斜方肌",
    difficulty: "intermediate",
    sets: "3-4组",
    reps: "20-30米/侧",
    description: "单手将壶铃或哑铃举过头顶，手臂完全伸直锁定，保持此姿势稳步行走。服务员行走对肩关节稳定性和核心抗侧屈能力有极高要求，是修复肩部功能和强化过头位稳定性的绝佳训练。单侧负重行走也能有效暴露身体的左右不对称问题。",
    tips: "手腕保持中立，肋骨下收，避免身体向对侧倾斜补偿。",
    color: "#229954"
  },
  {
    id: 19,
    name: "Suitcase Carry",
    nameZh: "手提箱行走",
    category: "carry",
    equipment: "壶铃",
    muscles: "腹斜肌、腰方肌、核心、前臂",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "30-40米/侧",
    description: "单手提一个壶铃或哑铃于身侧，如同提手提箱一样保持躯干正直稳步行走。该动作强烈刺激核心抗侧屈能力，尤其是腹斜肌和腰方肌。单侧负重行走是预防腰部伤害和提升运动中躯干稳定性的高效功能性训练。",
    tips: "负重侧身体不要倾斜，想象头顶有根线向上拉你保持挺直。",
    color: "#1E8449"
  },
  {
    id: 20,
    name: "Pallof Press",
    nameZh: "帕洛夫推",
    category: "core",
    equipment: "绳索",
    muscles: "腹横肌、腹斜肌、核心抗旋转肌群",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "10-12次/侧",
    description: "侧对绳索站立，双手持把手于胸前，将把手向前推出至手臂伸直，抵抗绳索的旋转拉力后收回。帕洛夫推是训练核心抗旋转能力的经典动作，直接提升运动中躯干抵抗外力扭转的稳定性。适用于各种球类运动和格斗项目的体能训练。",
    tips: "推出时缓慢控制，全程保持髋部和肩部正对前方。",
    color: "#F1C40F"
  },
  {
    id: 21,
    name: "Dead Bug",
    nameZh: "死虫子",
    category: "core",
    equipment: "自重",
    muscles: "腹直肌、腹横肌、髋屈肌",
    difficulty: "beginner",
    sets: "3组",
    reps: "8-10次/侧",
    description: "仰卧位双手指向天花板，双腿抬起膝盖弯曲90度，交替伸展对侧手臂和腿部同时保持腰部紧贴地面。死虫子是学习核心抗伸展控制的最佳入门动作，教会你在四肢运动时维持腰椎中立位。是康复训练和运动表现训练中最常用的核心激活练习。",
    tips: "全程保持下背部紧贴地面，腰部不能出现拱起。",
    color: "#F4D03F"
  },
  {
    id: 22,
    name: "Turkish Get-up",
    nameZh: "土耳其起立",
    category: "core",
    equipment: "壶铃",
    muscles: "全身（肩部、核心、臀部、腿部）",
    difficulty: "advanced",
    sets: "2-3组",
    reps: "3-5次/侧",
    description: "仰卧位单手持壶铃伸直过头，通过一系列精确的动作步骤从地面站起，再反向回到仰卧位。土耳其起立是最全面的功能性训练动作之一，整合了肩部稳定、核心控制、髋部灵活性和全身协调性。每一步都在训练不同的运动能力。",
    tips: "始终目视壶铃方向，每个过渡位置停顿确认姿势正确。",
    color: "#D4AC0D"
  },
  {
    id: 23,
    name: "Plank",
    nameZh: "平板支撑",
    category: "core",
    equipment: "自重",
    muscles: "腹横肌、腹直肌、竖脊肌",
    difficulty: "beginner",
    sets: "3组",
    reps: "30-60秒",
    description: "前臂撑地，身体从头到脚跟保持一条直线，收紧核心维持该姿势不动。平板支撑是最基础的核心抗伸展训练，教会核心肌群在静态条件下维持脊柱中立。虽然简单但对于建立核心稳定性的基础至关重要，是所有高级核心训练的起点。",
    tips: "夹紧臀部，前臂主动推离地面，避免肩膀塌陷和腰部下沉。",
    color: "#B7950B"
  },
  {
    id: 24,
    name: "Power Clean",
    nameZh: "高翻",
    category: "power",
    equipment: "杠铃",
    muscles: "臀大肌、股四头肌、斜方肌、三角肌",
    difficulty: "advanced",
    sets: "3-5组",
    reps: "3-5次",
    description: "杠铃从地面或悬垂位出发，通过爆发性伸髋伸膝将杠铃加速上拉，在最高点快速翻肘接住杠铃于前架位。高翻是发展全身爆发力的顶级训练动作，要求力量、速度和协调性的完美结合。是几乎所有竞技运动体能训练中的核心动作。",
    tips: "二次发力时三关节（踝、膝、髋）同时爆发伸展，手臂保持放松。",
    color: "#E67E22"
  },
  {
    id: 25,
    name: "Power Snatch",
    nameZh: "高抓",
    category: "power",
    equipment: "杠铃",
    muscles: "全身（臀部、背部、肩部、核心）",
    difficulty: "advanced",
    sets: "3-5组",
    reps: "2-4次",
    description: "宽握杠铃从地面起始，通过爆发性发力一次性将杠铃从地面拉至过头锁定位置。高抓是奥林匹克举重的基础动作之一，对全身爆发力、柔韧性和协调性有极高要求。掌握该动作能极大提升运动员的速度力量和快速发力能力。",
    tips: "杠铃紧贴身体上行，过膝后积极耸肩提肘，快速锁定过头。",
    color: "#D35400"
  },
  {
    id: 26,
    name: "Box Jump",
    nameZh: "跳箱",
    category: "power",
    equipment: "跳箱",
    muscles: "股四头肌、臀大肌、小腿三头肌",
    difficulty: "intermediate",
    sets: "3-4组",
    reps: "5-8次",
    description: "面对跳箱站立，快速屈髋屈膝摆臂后爆发性起跳，双脚同时落于箱面上后站直。跳箱是训练下肢爆发力和快速伸缩复合能力的经典动作，直接提升跳跃高度和起跑加速能力。落地时的缓冲控制也训练着离心力量和关节保护能力。",
    tips: "轻柔安静地落在箱子上，落地时膝盖微屈缓冲，不要硬砸。",
    color: "#F39C12"
  },
  {
    id: 27,
    name: "Med Ball Slam",
    nameZh: "药球砸地",
    category: "power",
    equipment: "药球",
    muscles: "背阔肌、腹直肌、三角肌、核心",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "10-15次",
    description: "双手将药球高举过头，通过全身爆发性发力将药球用力砸向地面。药球砸地是释放全身爆发力的高效训练动作，兼具力量和心肺训练效果。该动作模式与投掷、扣球等运动场景高度相关，同时也是极佳的压力释放训练。",
    tips: "砸球时主动收缩腹部，用全身力量而非仅靠手臂。",
    color: "#E74C3C"
  },
  {
    id: 28,
    name: "Hip 90/90",
    nameZh: "90/90髋关节拉伸",
    category: "mobility",
    equipment: "自重",
    muscles: "髋关节内外旋肌群、臀中肌、梨状肌",
    difficulty: "beginner",
    sets: "2-3组",
    reps: "8-10次/侧",
    description: "坐于地面，前腿和后腿各呈90度弯曲，交替向两侧转换，在每个位置停留并感受髋关节的拉伸。90/90是评估和改善髋关节内外旋灵活性的最佳动作，直接影响深蹲深度和运动中的变向能力。每天练习能显著改善髋关节的活动范围。",
    tips: "转换时保持脊柱直立，用臀部力量主动控制旋转。",
    color: "#1ABC9C"
  },
  {
    id: 29,
    name: "World's Greatest Stretch",
    nameZh: "世界最伟大拉伸",
    category: "mobility",
    equipment: "自重",
    muscles: "髋屈肌、胸椎旋转肌、腘绳肌、小腿",
    difficulty: "beginner",
    sets: "2-3组",
    reps: "5-6次/侧",
    description: "从弓步位置开始，同侧手肘触碰地面进行髋屈肌拉伸，然后旋转胸椎将手臂指向天花板。世界最伟大拉伸因其在一个动作中同时改善多个关节灵活性而得名，涵盖髋屈肌、胸椎旋转、腘绳肌和踝关节。是训练前热身和日常灵活性维护的首选动作。",
    tips: "胸椎旋转时目光跟随上方手掌，后腿膝盖不要触地。",
    color: "#16A085"
  },
  {
    id: 30,
    name: "Jefferson Curl",
    nameZh: "杰斐逊弯举",
    category: "mobility",
    equipment: "壶铃",
    muscles: "竖脊肌、腘绳肌、胸腰筋膜",
    difficulty: "intermediate",
    sets: "2-3组",
    reps: "5-8次",
    description: "站在高台边缘，持轻负重从颈椎开始逐节向下弯曲脊柱，双手向脚下方伸展，再逐节卷回起始位。杰斐逊弯举通过受控的脊柱屈曲训练增强脊柱在弯曲状态下的耐受力和柔韧性。该动作能有效改善后侧链的灵活性，但必须从极轻负重开始。",
    tips: "动作极缓慢，逐节脊椎滚动，绝不使用冲量，从空手开始。",
    color: "#148F77"
  }
];

const CATEGORY_LABELS = { push:"推", pull:"拉", squat:"蹲", hinge:"髋屈伸", carry:"负重行走", core:"核心", power:"爆发力", mobility:"灵活性" };
const CATEGORY_EMOJI = { push:"💪", pull:"🏋️", squat:"🦵", hinge:"🔗", carry:"🚶", core:"🎯", power:"⚡", mobility:"🧘" };
