const EXERCISES = [
  {
    id: 1,
    name: "Back Squat",
    nameZh: "杠铃深蹲",
    category: "squat",
    equipment: "杠铃",
    muscles: "股四头肌、臀大肌、竖脊肌",
    difficulty: "intermediate",
    sets: "3-5组",
    reps: "5-8次",
    description: "将杠铃置于上背部斜方肌位置，双脚与肩同宽，屈髋屈膝下蹲至大腿平行或略低于地面，再站起。杠铃深蹲是下肢力量训练之王，能有效提升运动表现中的加速、跳跃和变向能力。长期训练可显著增强核心稳定性和整体力量输出。",
    tips: "下蹲时膝盖沿脚尖方向打开，保持胸椎挺直，避免骨盆后倾。",
    color: "#E74C3C"
  },
  {
    id: 2,
    name: "Front Squat",
    nameZh: "前蹲",
    category: "squat",
    equipment: "杠铃",
    muscles: "股四头肌、臀大肌、上背部",
    difficulty: "intermediate",
    sets: "3-4组",
    reps: "6-10次",
    description: "杠铃置于锁骨与三角肌前束之间，采用交叉握或前架位握法。前蹲要求更直立的躯干姿态，对股四头肌和上背部的刺激更强。该动作对于提升举重技术和运动中的制动能力非常有帮助。",
    tips: "保持手肘高抬，上臂平行于地面，防止杠铃前滑。",
    color: "#C0392B"
  },
  {
    id: 3,
    name: "Bulgarian Split Squat",
    nameZh: "保加利亚分腿蹲",
    category: "squat",
    equipment: "哑铃",
    muscles: "股四头肌、臀大肌、髋屈肌",
    difficulty: "intermediate",
    sets: "3-4组",
    reps: "8-12次/侧",
    description: "后脚抬高置于长凳上，前脚向前一大步，手持哑铃做单腿下蹲。该动作能有效改善左右腿力量不平衡，同时拉伸后腿髋屈肌。是跑步、球类运动等需要单腿发力场景的最佳辅助训练之一。",
    tips: "前膝不超过脚尖过多，躯干保持直立，重心落在前脚全掌。",
    color: "#E67E22"
  },
  {
    id: 4,
    name: "Goblet Squat",
    nameZh: "高脚杯深蹲",
    category: "squat",
    equipment: "壶铃",
    muscles: "股四头肌、臀大肌、核心",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "10-15次",
    description: "双手捧住壶铃或哑铃置于胸前，双脚略宽于肩站立，下蹲至最低位置。高脚杯深蹲是学习正确深蹲模式的最佳入门动作，前置负重自然引导直立的躯干姿态。适合初学者建立良好的下肢运动模式和基础力量。",
    tips: "下蹲底部用肘部轻推膝盖内侧向外，充分打开髋关节。",
    color: "#F39C12"
  },
  {
    id: 5,
    name: "Pistol Squat",
    nameZh: "单腿深蹲",
    category: "squat",
    equipment: "自重",
    muscles: "股四头肌、臀大肌、踝关节稳定肌",
    difficulty: "advanced",
    sets: "3-4组",
    reps: "3-6次/侧",
    description: "单腿站立，另一条腿向前伸直悬空，缓慢下蹲至最低点后站起。单腿深蹲是自重训练中最具挑战性的下肢动作，要求极高的单腿力量、平衡感和踝关节灵活性。掌握该动作意味着你拥有出色的功能性下肢能力。",
    tips: "初学者可手扶门框或使用弹力带辅助，逐步减少辅助量。",
    color: "#D35400"
  },
  {
    id: 6,
    name: "Push-up",
    nameZh: "俯卧撑",
    category: "push",
    equipment: "自重",
    muscles: "胸大肌、三角肌前束、肱三头肌",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "10-20次",
    description: "双手撑地略宽于肩，身体从头到脚保持一条直线，屈肘下降胸部接近地面后推起。俯卧撑是最经典的功能性推力训练，无需任何器械即可有效锻炼上肢推力链。同时对核心抗伸展稳定性有很好的训练效果。",
    tips: "全程收紧臀部和腹部，避免腰部塌陷或翘臀。",
    color: "#3498DB"
  },
  {
    id: 7,
    name: "Overhead Press",
    nameZh: "杠铃过头推举",
    category: "push",
    equipment: "杠铃",
    muscles: "三角肌、肱三头肌、上斜方肌",
    difficulty: "intermediate",
    sets: "3-5组",
    reps: "5-8次",
    description: "杠铃从锁骨前方起始，双手略宽于肩握杠，将杠铃垂直推举过头至手臂完全伸直。过头推举是衡量上肢推力力量的黄金标准动作，对肩关节稳定性和整体上肢力量的发展至关重要。运动员掌握这个动作能提升投掷、格斗等场景的表现。",
    tips: "推举时头部微微后收让杠铃通过，锁定后头部回到杠铃正下方。",
    color: "#2980B9"
  },
  {
    id: 8,
    name: "Bench Press",
    nameZh: "卧推",
    category: "push",
    equipment: "杠铃",
    muscles: "胸大肌、三角肌前束、肱三头肌",
    difficulty: "intermediate",
    sets: "3-5组",
    reps: "5-10次",
    description: "仰卧于卧推凳上，双手握杠铃下放至胸部中下端，停顿后推起至手臂伸直。卧推是上肢水平推力的基础训练，能显著提升推力方向的最大力量。对于需要推挡、格斗、橄榄球等推力需求的运动员尤为重要。",
    tips: "肩胛骨收紧下沉贴紧凳面，双脚踩实地面，建立稳定的力量传导链。",
    color: "#1ABC9C"
  },
  {
    id: 9,
    name: "Dips",
    nameZh: "双杠臂屈伸",
    category: "push",
    equipment: "双杠",
    muscles: "胸大肌下部、肱三头肌、三角肌前束",
    difficulty: "intermediate",
    sets: "3-4组",
    reps: "8-12次",
    description: "双手撑于平行双杠上，身体悬空，屈肘下降至上臂与地面平行后推起。双杠臂屈伸是一个优秀的上肢推力复合动作，可通过身体前倾角度调节胸肌和肱三头肌的参与比例。也是体操和街头健身的核心基础动作。",
    tips: "身体前倾约15-30度更多刺激胸肌，保持直立则侧重肱三头肌。",
    color: "#16A085"
  },
  {
    id: 10,
    name: "Pull-up",
    nameZh: "引体向上",
    category: "pull",
    equipment: "单杠",
    muscles: "背阔肌、肱二头肌、菱形肌",
    difficulty: "intermediate",
    sets: "3-5组",
    reps: "5-10次",
    description: "双手正握单杠略宽于肩，从完全悬垂位置拉起身体直到下巴超过杠面。引体向上是衡量相对力量的最佳指标之一，对攀爬、格斗抓握等运动场景至关重要。该动作高效发展整个后侧链的拉力能力。",
    tips: "起始时先下沉肩胛骨激活背部，避免纯靠手臂弯曲完成动作。",
    color: "#9B59B6"
  },
  {
    id: 11,
    name: "Barbell Row",
    nameZh: "杠铃划船",
    category: "pull",
    equipment: "杠铃",
    muscles: "背阔肌、菱形肌、后三角肌、肱二头肌",
    difficulty: "intermediate",
    sets: "3-4组",
    reps: "6-10次",
    description: "俯身约45度角，双手正握杠铃，将杠铃拉向下腹部，肩胛骨充分收缩后缓慢放下。杠铃划船是发展背部厚度和水平拉力的核心动作。强壮的划船能力直接转化为更好的体姿控制和运动中的拉扯对抗能力。",
    tips: "保持下背部自然弧度，避免借助躯干摆动发力。",
    color: "#8E44AD"
  },
  {
    id: 12,
    name: "Face Pull",
    nameZh: "面拉",
    category: "pull",
    equipment: "绳索",
    muscles: "后三角肌、菱形肌、外旋肌群",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "15-20次",
    description: "使用绳索附件设置于面部高度，双手握绳向面部拉动，同时外旋肩关节至手在耳朵两侧。面拉是维护肩关节健康最重要的辅助动作，能有效强化经常被忽视的后三角肌和肩外旋肌群。建议每次训练都包含该动作以平衡推拉比例。",
    tips: "拉到终点时挤压肩胛骨，想象两只手要碰到耳朵后方。",
    color: "#7D3C98"
  },
  {
    id: 13,
    name: "Deadlift",
    nameZh: "硬拉",
    category: "hinge",
    equipment: "杠铃",
    muscles: "竖脊肌、臀大肌、腘绳肌、斜方肌",
    difficulty: "intermediate",
    sets: "3-5组",
    reps: "3-6次",
    description: "双脚与髋同宽站立于杠铃后方，屈髋屈膝握住杠铃，通过伸髋伸膝将杠铃从地面拉起至完全站直。硬拉是人体能完成的最大负重动作之一，训练整个后侧链的协同发力。对于提升运动爆发力、抗伤害能力和整体力量水平有不可替代的作用。",
    tips: "杠铃紧贴身体上行，保持背部中立，起始发力先蹬地再伸髋。",
    color: "#2C3E50"
  },
  {
    id: 14,
    name: "Romanian Deadlift",
    nameZh: "罗马尼亚硬拉",
    category: "hinge",
    equipment: "杠铃",
    muscles: "腘绳肌、臀大肌、竖脊肌",
    difficulty: "intermediate",
    sets: "3-4组",
    reps: "8-12次",
    description: "站立位持杠铃，膝盖微屈，以髋关节为轴心将躯干前倾，杠铃沿大腿前侧下降至感到腘绳肌强烈拉伸后伸髋回起。罗马尼亚硬拉专注于髋铰链模式的离心控制，是发展腘绳肌力量和预防后侧链损伤的核心训练动作。",
    tips: "想象用臀部去碰身后的墙壁，保持杠铃紧贴大腿。",
    color: "#34495E"
  },
  {
    id: 15,
    name: "Kettlebell Swing",
    nameZh: "壶铃摆荡",
    category: "hinge",
    equipment: "壶铃",
    muscles: "臀大肌、腘绳肌、核心、前臂",
    difficulty: "beginner",
    sets: "3-5组",
    reps: "15-20次",
    description: "双手握壶铃站立，通过爆发性伸髋将壶铃摆至与肩同高，利用重力下落的惯性再次屈髋完成下一次摆动。壶铃摆荡是发展髋部爆发力和心肺耐力的高效动作，兼具力量训练和有氧训练的双重效果。短时间内即可达到极高的训练效率。",
    tips: "力量来源于髋部爆发而非手臂上拉，在最高点挤紧臀部。",
    color: "#E74C3C"
  },
  {
    id: 16,
    name: "Hip Thrust",
    nameZh: "臀推",
    category: "hinge",
    equipment: "杠铃",
    muscles: "臀大肌、腘绳肌",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "8-12次",
    description: "上背部靠在长凳边缘，杠铃放于髋部位置，双脚踩地与髋同宽，通过伸髋将杠铃顶起直到躯干与大腿平行。臀推是针对臀大肌最大化激活的动作，对提升冲刺速度、跳跃高度和髋伸展力量有直接帮助。很多运动员将其作为核心训练动作之一。",
    tips: "顶峰位置保持1-2秒挤压臀部，避免过度伸展腰椎。",
    color: "#A93226"
  },
  {
    id: 17,
    name: "Farmer's Walk",
    nameZh: "农夫行走",
    category: "carry",
    equipment: "哑铃",
    muscles: "斜方肌、前臂、核心、全身",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "30-40米",
    description: "双手各持一个重哑铃或专用农夫行走把手，保持挺胸收腹的姿态稳步行走规定距离。农夫行走是最具功能性的训练动作之一，同时训练握力、核心稳定性、肩部承载能力和整体体能。该动作模拟日常搬运重物的场景，实用性极强。",
    tips: "肩膀下沉远离耳朵，目视前方，步幅适中保持稳定。",
    color: "#27AE60"
  },
  {
    id: 18,
    name: "Waiter's Walk",
    nameZh: "服务员行走",
    category: "carry",
    equipment: "壶铃",
    muscles: "三角肌、核心抗侧屈肌群、斜方肌",
    difficulty: "intermediate",
    sets: "3-4组",
    reps: "20-30米/侧",
    description: "单手将壶铃或哑铃举过头顶，手臂完全伸直锁定，保持此姿势稳步行走。服务员行走对肩关节稳定性和核心抗侧屈能力有极高要求，是修复肩部功能和强化过头位稳定性的绝佳训练。单侧负重行走也能有效暴露身体的左右不对称问题。",
    tips: "手腕保持中立，肋骨下收，避免身体向对侧倾斜补偿。",
    color: "#229954"
  },
  {
    id: 19,
    name: "Suitcase Carry",
    nameZh: "手提箱行走",
    category: "carry",
    equipment: "壶铃",
    muscles: "腹斜肌、腰方肌、核心、前臂",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "30-40米/侧",
    description: "单手提一个壶铃或哑铃于身侧，如同提手提箱一样保持躯干正直稳步行走。该动作强烈刺激核心抗侧屈能力，尤其是腹斜肌和腰方肌。单侧负重行走是预防腰部伤害和提升运动中躯干稳定性的高效功能性训练。",
    tips: "负重侧身体不要倾斜，想象头顶有根线向上拉你保持挺直。",
    color: "#1E8449"
  },
  {
    id: 20,
    name: "Pallof Press",
    nameZh: "帕洛夫推",
    category: "core",
    equipment: "绳索",
    muscles: "腹横肌、腹斜肌、核心抗旋转肌群",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "10-12次/侧",
    description: "侧对绳索站立，双手持把手于胸前，将把手向前推出至手臂伸直，抵抗绳索的旋转拉力后收回。帕洛夫推是训练核心抗旋转能力的经典动作，直接提升运动中躯干抵抗外力扭转的稳定性。适用于各种球类运动和格斗项目的体能训练。",
    tips: "推出时缓慢控制，全程保持髋部和肩部正对前方。",
    color: "#F1C40F"
  },
  {
    id: 21,
    name: "Dead Bug",
    nameZh: "死虫子",
    category: "core",
    equipment: "自重",
    muscles: "腹直肌、腹横肌、髋屈肌",
    difficulty: "beginner",
    sets: "3组",
    reps: "8-10次/侧",
    description: "仰卧位双手指向天花板，双腿抬起膝盖弯曲90度，交替伸展对侧手臂和腿部同时保持腰部紧贴地面。死虫子是学习核心抗伸展控制的最佳入门动作，教会你在四肢运动时维持腰椎中立位。是康复训练和运动表现训练中最常用的核心激活练习。",
    tips: "全程保持下背部紧贴地面，腰部不能出现拱起。",
    color: "#F4D03F"
  },
  {
    id: 22,
    name: "Turkish Get-up",
    nameZh: "土耳其起立",
    category: "core",
    equipment: "壶铃",
    muscles: "全身（肩部、核心、臀部、腿部）",
    difficulty: "advanced",
    sets: "2-3组",
    reps: "3-5次/侧",
    description: "仰卧位单手持壶铃伸直过头，通过一系列精确的动作步骤从地面站起，再反向回到仰卧位。土耳其起立是最全面的功能性训练动作之一，整合了肩部稳定、核心控制、髋部灵活性和全身协调性。每一步都在训练不同的运动能力。",
    tips: "始终目视壶铃方向，每个过渡位置停顿确认姿势正确。",
    color: "#D4AC0D"
  },
  {
    id: 23,
    name: "Plank",
    nameZh: "平板支撑",
    category: "core",
    equipment: "自重",
    muscles: "腹横肌、腹直肌、竖脊肌",
    difficulty: "beginner",
    sets: "3组",
    reps: "30-60秒",
    description: "前臂撑地，身体从头到脚跟保持一条直线，收紧核心维持该姿势不动。平板支撑是最基础的核心抗伸展训练，教会核心肌群在静态条件下维持脊柱中立。虽然简单但对于建立核心稳定性的基础至关重要，是所有高级核心训练的起点。",
    tips: "夹紧臀部，前臂主动推离地面，避免肩膀塌陷和腰部下沉。",
    color: "#B7950B"
  },
  {
    id: 24,
    name: "Power Clean",
    nameZh: "高翻",
    category: "power",
    equipment: "杠铃",
    muscles: "臀大肌、股四头肌、斜方肌、三角肌",
    difficulty: "advanced",
    sets: "3-5组",
    reps: "3-5次",
    description: "杠铃从地面或悬垂位出发，通过爆发性伸髋伸膝将杠铃加速上拉，在最高点快速翻肘接住杠铃于前架位。高翻是发展全身爆发力的顶级训练动作，要求力量、速度和协调性的完美结合。是几乎所有竞技运动体能训练中的核心动作。",
    tips: "二次发力时三关节（踝、膝、髋）同时爆发伸展，手臂保持放松。",
    color: "#E67E22"
  },
  {
    id: 25,
    name: "Power Snatch",
    nameZh: "高抓",
    category: "power",
    equipment: "杠铃",
    muscles: "全身（臀部、背部、肩部、核心）",
    difficulty: "advanced",
    sets: "3-5组",
    reps: "2-4次",
    description: "宽握杠铃从地面起始，通过爆发性发力一次性将杠铃从地面拉至过头锁定位置。高抓是奥林匹克举重的基础动作之一，对全身爆发力、柔韧性和协调性有极高要求。掌握该动作能极大提升运动员的速度力量和快速发力能力。",
    tips: "杠铃紧贴身体上行，过膝后积极耸肩提肘，快速锁定过头。",
    color: "#D35400"
  },
  {
    id: 26,
    name: "Box Jump",
    nameZh: "跳箱",
    category: "power",
    equipment: "跳箱",
    muscles: "股四头肌、臀大肌、小腿三头肌",
    difficulty: "intermediate",
    sets: "3-4组",
    reps: "5-8次",
    description: "面对跳箱站立，快速屈髋屈膝摆臂后爆发性起跳，双脚同时落于箱面上后站直。跳箱是训练下肢爆发力和快速伸缩复合能力的经典动作，直接提升跳跃高度和起跑加速能力。落地时的缓冲控制也训练着离心力量和关节保护能力。",
    tips: "轻柔安静地落在箱子上，落地时膝盖微屈缓冲，不要硬砸。",
    color: "#F39C12"
  },
  {
    id: 27,
    name: "Med Ball Slam",
    nameZh: "药球砸地",
    category: "power",
    equipment: "药球",
    muscles: "背阔肌、腹直肌、三角肌、核心",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "10-15次",
    description: "双手将药球高举过头，通过全身爆发性发力将药球用力砸向地面。药球砸地是释放全身爆发力的高效训练动作，兼具力量和心肺训练效果。该动作模式与投掷、扣球等运动场景高度相关，同时也是极佳的压力释放训练。",
    tips: "砸球时主动收缩腹部，用全身力量而非仅靠手臂。",
    color: "#E74C3C"
  },
  {
    id: 28,
    name: "Hip 90/90",
    nameZh: "90/90髋关节拉伸",
    category: "mobility",
    equipment: "自重",
    muscles: "髋关节内外旋肌群、臀中肌、梨状肌",
    difficulty: "beginner",
    sets: "2-3组",
    reps: "8-10次/侧",
    description: "坐于地面，前腿和后腿各呈90度弯曲，交替向两侧转换，在每个位置停留并感受髋关节的拉伸。90/90是评估和改善髋关节内外旋灵活性的最佳动作，直接影响深蹲深度和运动中的变向能力。每天练习能显著改善髋关节的活动范围。",
    tips: "转换时保持脊柱直立，用臀部力量主动控制旋转。",
    color: "#1ABC9C"
  },
  {
    id: 29,
    name: "World's Greatest Stretch",
    nameZh: "世界最伟大拉伸",
    category: "mobility",
    equipment: "自重",
    muscles: "髋屈肌、胸椎旋转肌、腘绳肌、小腿",
    difficulty: "beginner",
    sets: "2-3组",
    reps: "5-6次/侧",
    description: "从弓步位置开始，同侧手肘触碰地面进行髋屈肌拉伸，然后旋转胸椎将手臂指向天花板。世界最伟大拉伸因其在一个动作中同时改善多个关节灵活性而得名，涵盖髋屈肌、胸椎旋转、腘绳肌和踝关节。是训练前热身和日常灵活性维护的首选动作。",
    tips: "胸椎旋转时目光跟随上方手掌，后腿膝盖不要触地。",
    color: "#16A085"
  },
  {
    id: 30,
    name: "Jefferson Curl",
    nameZh: "杰斐逊弯举",
    category: "mobility",
    equipment: "壶铃",
    muscles: "竖脊肌、腘绳肌、胸腰筋膜",
    difficulty: "intermediate",
    sets: "2-3组",
    reps: "5-8次",
    description: "站在高台边缘，持轻负重从颈椎开始逐节向下弯曲脊柱，双手向脚下方伸展，再逐节卷回起始位。杰斐逊弯举通过受控的脊柱屈曲训练增强脊柱在弯曲状态下的耐受力和柔韧性。该动作能有效改善后侧链的灵活性，但必须从极轻负重开始。",
    tips: "动作极缓慢，逐节脊椎滚动，绝不使用冲量，从空手开始。",
    color: "#148F77"
  },
  {
    id: 31,
    name: "Terminal Knee Extension (TKE)",
    nameZh: "终末膝伸展（TKE）",
    category: "rehab",
    equipment: "弹力带",
    muscles: "股内侧肌（VMO）、股四头肌",
    difficulty: "beginner",
    sets: "3组",
    reps: "15-20次/侧",
    description: "将弹力带环绕固定点后套在膝关节后方，面对固定点站立使弹力带产生向前拉力，从膝盖微屈位主动伸直膝关节并挤紧。TKE通过弹力带在膝关节后方施加前向阻力，专门强化股内侧肌（VMO）在膝伸展最后15度的控制能力，改善髌骨轨迹异常。VMO的激活不足是髌股关节疼痛和膝关节不稳的首要原因，该动作是膝关节康复早期最安全有效的闭链训练。",
    tips: "伸膝到顶端时主动挤紧大腿内侧肌肉，保持2秒再缓慢放松。",
    color: "#45B7D1"
  },
  {
    id: 32,
    name: "Wall Sit",
    nameZh: "靠墙静蹲",
    category: "rehab",
    equipment: "自重",
    muscles: "股四头肌、臀大肌",
    difficulty: "beginner",
    sets: "3-4组",
    reps: "30-45秒",
    description: "背靠墙壁，双脚前移一步，缓慢下滑至大腿与地面接近平行位置并静态保持。靠墙静蹲通过等长收缩方式加载膝关节周围肌群，在不产生关节面剪切力的前提下增强股四头肌力量和肌腱耐受性。等长训练已被证实能有效缓解髌腱炎疼痛并促进肌腱重塑，是膝关节康复中期最核心的训练方式之一。",
    tips: "膝盖弯曲角度根据疼痛耐受调整（60-90度），背部完全贴墙不要拱起。",
    color: "#4ECDC4"
  },
  {
    id: 33,
    name: "Straight Leg Raise (SLR)",
    nameZh: "直腿抬高",
    category: "rehab",
    equipment: "自重",
    muscles: "股四头肌、髋屈肌",
    difficulty: "beginner",
    sets: "3组",
    reps: "12-15次/侧",
    description: "仰卧位一腿弯曲踩地，另一腿完全伸直并收紧股四头肌，将直腿抬高至约45度后缓慢放下。直腿抬高在膝关节零负荷状态下训练股四头肌的主动收缩能力，是ACL术后和膝关节急性损伤早期最安全的肌力恢复训练。通过锁定膝关节伸直位避免了任何关节内摩擦，同时重建大脑对股四头肌的神经募集能力，解决术后常见的股四头肌抑制问题。",
    tips: "抬腿前先用力收紧大腿使膝盖完全锁直，脚尖勾起朝向自己。",
    color: "#96CEB4"
  },
  {
    id: 34,
    name: "Step-down Eccentric Control",
    nameZh: "台阶下落离心控制",
    category: "rehab",
    equipment: "台阶/踏板",
    muscles: "股四头肌、臀中肌、踝关节稳定肌",
    difficulty: "intermediate",
    sets: "3组",
    reps: "8-10次/侧",
    description: "单腿站在台阶边缘，悬空腿缓慢向下伸展，脚跟轻触地面后用站立腿推回起始位。台阶下落训练专注于股四头肌的离心收缩控制——这正是下楼梯、下坡跑步时膝关节疼痛的根本原因。离心训练能促进肌腱胶原纤维的有序重排，是治疗髌腱病变的金标准方案（Alfredson方案核心原理），同时训练单腿稳定性和骨盆水平控制。",
    tips: "下落速度控制在3-4秒，骨盆保持水平不要侧倾，膝盖对准第二脚趾方向。",
    color: "#FFEAA7"
  },
  {
    id: 35,
    name: "Single-leg Balance on Unstable Surface",
    nameZh: "不稳定面单腿站立",
    category: "rehab",
    equipment: "平衡垫/BOSU球",
    muscles: "踝关节本体感觉肌群、臀中肌、胫骨前肌",
    difficulty: "beginner",
    sets: "3组",
    reps: "30-45秒/侧",
    description: "单脚站在平衡垫或BOSU球上，保持身体稳定不晃动。不稳定面平衡训练通过持续刺激踝膝髋三个关节的本体感受器，重建关节损伤后丧失的神经肌肉控制能力。韧带损伤（如ACL、踝关节扭伤）后本体感觉显著下降是再次受伤的首要风险因素，该训练能有效恢复关节位置觉和动态稳定反射，降低二次损伤风险达50%以上。",
    tips: "支撑腿膝盖保持微屈（约15度），目视前方固定点，感受脚底三点（大脚趾、小脚趾、脚跟）均匀受力。",
    color: "#DDA0DD"
  },
  {
    id: 36,
    name: "Hamstring Curl with Swiss Ball",
    nameZh: "瑞士球腘绳肌弯举",
    category: "rehab",
    equipment: "瑞士球",
    muscles: "腘绳肌、臀大肌、核心",
    difficulty: "intermediate",
    sets: "3组",
    reps: "10-12次",
    description: "仰卧位双脚跟置于瑞士球上，抬起臀部成桥式，然后弯曲膝盖将球滚向臀部方向，再缓慢推回伸直。瑞士球腘绳肌弯举在闭链条件下同时训练腘绳肌的膝屈和髋伸功能，弥补ACL损伤后腘绳肌作为膝关节动态稳定器的力量不足。腘绳肌与ACL协同防止胫骨前移，强化腘绳肌能有效替代受损ACL的部分功能，是ACL康复和预防的关键训练。",
    tips: "臀部全程保持抬高不要塌落，回球时控制3秒离心，感受腘绳肌持续发力。",
    color: "#C39BD3"
  },
  {
    id: 37,
    name: "Clamshell with Band",
    nameZh: "蚌式开合（弹力带）",
    category: "rehab",
    equipment: "弹力带",
    muscles: "臀中肌、臀小肌、髋外旋肌群",
    difficulty: "beginner",
    sets: "3组",
    reps: "15-20次/侧",
    description: "侧卧位，弹力带套在双膝上方，双膝弯曲约90度，双脚并拢不动，上方膝盖像蚌壳一样向上打开再缓慢合拢。蚌式开合是激活臀中肌最精准的入门动作——臀中肌无力是导致膝外翻（膝盖内扣）的根本原因。当臀中肌无法有效控制股骨内旋和内收时，膝关节在跑步、跳跃落地时被迫内扣，造成ACL和半月板的巨大应力。该动作通过髋外旋和外展模式重建臀中肌的神经激活通路。",
    tips: "骨盆保持垂直不要向后滚动，打开时想象用膝盖去碰身后的墙壁，速度要慢。",
    color: "#F0B27A"
  },
  {
    id: 38,
    name: "Banded Lateral Walk",
    nameZh: "弹力带螃蟹步",
    category: "rehab",
    equipment: "弹力带",
    muscles: "臀中肌、臀小肌、阔筋膜张肌",
    difficulty: "beginner",
    sets: "3组",
    reps: "12-15步/方向",
    description: "弹力带套在脚踝或膝盖上方，保持半蹲姿势，向侧方交替迈步行走。弹力带螃蟹步通过持续的侧向阻力强迫臀中肌在功能性姿势下（屈髋屈膝）维持高强度激活，直接纠正运动中膝外翻的动态模式。研究表明臀中肌在该动作中的EMG激活水平超过最大随意收缩的70%，是从卧位臀中肌激活过渡到站立位功能性训练的最佳桥梁动作。",
    tips: "始终保持半蹲姿势不要站直，迈步时膝盖持续对准脚尖方向，不要内扣。",
    color: "#EB984E"
  },
  {
    id: 39,
    name: "Single-leg Romanian Deadlift",
    nameZh: "单腿罗马尼亚硬拉",
    category: "rehab",
    equipment: "哑铃",
    muscles: "臀中肌、臀大肌、腘绳肌、髋关节稳定肌群",
    difficulty: "intermediate",
    sets: "3组",
    reps: "8-10次/侧",
    description: "单腿站立手持哑铃，以髋关节为轴心前倾躯干同时后腿向后伸展，形成T字形后回到站立位。单腿罗马尼亚硬拉在矢状面运动中挑战额状面稳定性，强迫臀中肌在负重单腿支撑时控制骨盆水平和股骨内旋。该动作整合了臀大肌的伸髋力量和臀中肌的骨盆稳定功能，是纠正膝外翻的最高级功能性训练，直接模拟跑步单腿着地时的力学需求。",
    tips: "支撑腿膝盖微屈，骨盆全程保持朝向地面不要旋转打开，后腿脚尖朝下。",
    color: "#E59866"
  },
  {
    id: 40,
    name: "Toe Splay Exercise",
    nameZh: "脚趾展开练习",
    category: "rehab",
    equipment: "自重",
    muscles: "趾展肌、拇展肌、小趾展肌",
    difficulty: "beginner",
    sets: "3组",
    reps: "10-15次",
    description: "赤脚坐立，主动将所有脚趾尽可能向两侧展开撑大，保持3-5秒后放松。脚趾展开练习直接强化拇展肌——这块肌肉的萎缩和失活是拇外翻进展的核心病理因素。当拇展肌无力时，拇内收肌和第一跖趾关节外侧结构失衡，将大脚趾持续拉向外翻方向。通过反复主动外展训练，能重建拇展肌的神经控制和肌力，对抗拇外翻的生物力学异常。",
    tips: "初期如果无法单独控制脚趾展开，可用手辅助分开脚趾后再尝试主动维持，每天赤脚练习效果更佳。",
    color: "#82E0AA"
  },
  {
    id: 41,
    name: "Short Foot Exercise",
    nameZh: "缩足运动（足弓激活）",
    category: "rehab",
    equipment: "自重",
    muscles: "足底内在肌群、胫骨后肌、拇展肌",
    difficulty: "beginner",
    sets: "3组",
    reps: "10-12次/侧",
    description: "赤脚站立或坐姿，在脚趾不屈曲抓地的前提下，主动将第一跖骨头向脚跟方向缩拢，使足弓抬高变短。缩足运动是激活足底内在肌群（尤其是拇展肌和蚓状肌）的金标准训练，能重建塌陷的内侧纵弓。足弓塌陷是拇外翻的上游诱因——当内侧纵弓下降时，第一跖骨被迫内翻，大脚趾相对外翻角度增大。通过恢复足弓的主动支撑能力，从根源改善拇外翻的力学环境。",
    tips: "注意脚趾要保持平放不要屈曲扣地，想象把脚底中心向上吸起来，大脚趾根部用力压住地面。",
    color: "#73C6B6"
  },
  {
    id: 42,
    name: "Big Toe Press and Lift Isolation",
    nameZh: "大脚趾独立按压与抬起",
    category: "rehab",
    equipment: "自重",
    muscles: "拇展肌、拇长屈肌、拇长伸肌",
    difficulty: "beginner",
    sets: "3组",
    reps: "12-15次/侧",
    description: "赤脚坐姿或站姿，先将大脚趾用力下压地面同时其余四趾抬起，然后反过来将大脚趾抬起同时其余四趾下压。该动作训练大脚趾的独立运动控制能力，恢复拇长屈肌、拇长伸肌和拇展肌的协调发力模式。拇外翻患者通常丧失了大脚趾的独立运动能力，导致步态中蹬地推进阶段大脚趾无法有效承重，进一步加速拇外翻恶化。重建大脚趾的精细运动控制是恢复正常步态生物力学的关键。",
    tips: "动作要慢，专注于大脚趾与其余四趾的分离控制，初期可以用手辅助感受正确的运动方向。",
    color: "#58D68D"
  }
];

const CATEGORY_LABELS = { push:"推", pull:"拉", squat:"蹲", hinge:"髋屈伸", carry:"负重行走", core:"核心", power:"爆发力", mobility:"灵活性", rehab:"康复训练" };
const CATEGORY_EMOJI = { push:"💪", pull:"🏋️", squat:"🦵", hinge:"🔗", carry:"🚶", core:"🎯", power:"⚡", mobility:"🧘", rehab:"🦵" };
