const SKI_RESORTS = [
  {
    id: 1,
    name: "Niseko",
    nameZh: "二世古",
    region: "日本",
    country: "Japan",
    difficulty: "intermediate",
    trails: "80+条雪道",
    vertical: "1,000m落差",
    season: "12月-4月",
    snowfall: "年均15m",
    highlights: "二世古以世界顶级的粉雪闻名，每年降雪量惊人，被誉为粉雪天堂。四座相连的滑雪场提供广阔的滑雪区域，夜场滑雪体验也极为出色。山下温泉村落充满日式风情，滑雪后泡汤是绝佳享受。",
    tips: "建议购买全山联票，可自由穿梭四座雪场；夜场至晚上8点，性价比极高。",
    color: "#4A90D9"
  },
  {
    id: 2,
    name: "Hakuba",
    nameZh: "白马",
    region: "日本",
    country: "Japan",
    difficulty: "advanced",
    trails: "200+条雪道",
    vertical: "1,071m落差",
    season: "12月-5月",
    snowfall: "年均11m",
    highlights: "白马是1998年冬奥会举办地，拥有日本规模最大的滑雪区域。十座雪场相连，地形多样，从初学者到专家都能找到适合的雪道。壮观的北阿尔卑斯山脉景色令人叹为观止。",
    tips: "推荐白马八方尾根雪场的高山景观路线；从东京乘坐巴士约5小时可达。",
    color: "#5BA3E6"
  },
  {
    id: 3,
    name: "Myoko Kogen",
    nameZh: "妙高高原",
    region: "日本",
    country: "Japan",
    difficulty: "intermediate",
    trails: "60+条雪道",
    vertical: "1,124m落差",
    season: "12月-4月",
    snowfall: "年均14m",
    highlights: "妙高高原拥有日本最大的降雪量之一，粉雪质量媲美二世古。雪场游客相对较少，能享受更纯粹的滑雪体验。周边温泉资源丰富，赤�的温泉以独特的红褐色泉水闻名。",
    tips: "从东京乘新干线到上越妙高站仅需2小时，再换乘巴士30分钟即达。",
    color: "#6DB3F0"
  },
  {
    id: 4,
    name: "Nozawa Onsen",
    nameZh: "野�的温泉",
    region: "日本",
    country: "Japan",
    difficulty: "intermediate",
    trails: "50+条雪道",
    vertical: "1,085m落差",
    season: "12月-5月",
    snowfall: "年均12m",
    highlights: "野泽温泉是日本最古老的滑雪胜地之一，完美融合了传统温泉文化与现代滑雪设施。村中13处免费公共温泉是其最大特色。每年1月的道祖神火祭是日本三大火祭之一，不容错过。",
    tips: "村内免费温泉无需预约，建议自带毛巾；火祭期间住宿需提前数月预订。",
    color: "#7EC4FA"
  },
  {
    id: 5,
    name: "Furano",
    nameZh: "富良野",
    region: "日本",
    country: "Japan",
    difficulty: "beginner",
    trails: "40+条雪道",
    vertical: "964m落差",
    season: "11月-5月",
    snowfall: "年均9m",
    highlights: "富良野以优质的干粉雪和较少的游客著称，是北海道的隐藏宝石。雪场分为富良野区和北之峰区，适合家庭和初中级滑雪者。夏季的薰衣草花田同样闻名世界。",
    tips: "建议入住王子酒店可直达雪场；附近的「森林精灵露台」木屋群值得一游。",
    color: "#8FD4FF"
  },
  {
    id: 6,
    name: "Chamonix-Mont-Blanc",
    nameZh: "霞慕尼-勃朗峰",
    region: "法国",
    country: "France",
    difficulty: "expert",
    trails: "170+条雪道",
    vertical: "2,807m落差",
    season: "12月-4月",
    snowfall: "年均8m",
    highlights: "霞慕尼坐落于欧洲最高峰勃朗峰脚下，是现代登山运动的发源地和首届冬奥会举办地。Vallée Blanche是全球最著名的野雪路线之一，20公里的冰川滑降令人终生难忘。极限地形和壮阔景观吸引着全球顶尖滑雪者。",
    tips: "Vallée Blanche需聘请持证向导；南针峰缆车常因大风停运，建议留出备用日。",
    color: "#1E3A5F"
  },
  {
    id: 7,
    name: "Val Thorens",
    nameZh: "瓦尔托朗",
    region: "法国",
    country: "France",
    difficulty: "intermediate",
    trails: "150+条雪道",
    vertical: "1,300m落差",
    season: "11月-5月",
    snowfall: "年均7m",
    highlights: "瓦尔托朗是欧洲海拔最高的滑雪站（2,300m），雪季超长且雪质极佳。作为三峡谷滑雪区的最高点，可直接连通世界最大的相连滑雪区域。现代化的度假村设施齐全，夜生活丰富多彩。",
    tips: "持三峡谷联票可畅滑600公里雪道；高海拔紫外线强烈，务必做好防晒。",
    color: "#2B4F7A"
  },
  {
    id: 8,
    name: "Les 3 Vallées",
    nameZh: "三峡谷",
    region: "法国",
    country: "France",
    difficulty: "intermediate",
    trails: "330+条雪道",
    vertical: "2,000m落差",
    season: "12月-4月",
    snowfall: "年均6m",
    highlights: "三峡谷是全球最大的相连滑雪区，涵盖600公里标记雪道，串联八座度假村。从初学者的宽阔绿道到专家级的陡坡，地形选择无与伦比。一张雪票即可体验无尽的滑雪可能。",
    tips: "建议至少安排5天以上才能充分体验全域；推荐住在梅里贝尔，位置居中交通便利。",
    color: "#3D6595"
  },
  {
    id: 9,
    name: "Zermatt",
    nameZh: "采尔马特",
    region: "瑞士",
    country: "Switzerland",
    difficulty: "advanced",
    trails: "200+条雪道",
    vertical: "2,279m落差",
    season: "全年开放",
    snowfall: "年均5m",
    highlights: "采尔马特坐落于标志性的马特洪峰脚下，是全球少数提供全年滑雪的度假村。禁止燃油汽车进入的无车小镇保留了阿尔卑斯传统风情。与意大利切尔维尼亚相连，构成阿尔卑斯最高的滑雪区域。",
    tips: "小镇禁止汽车通行，需在塔什换乘火车进入；夏季冰川滑雪仅开放部分区域。",
    color: "#C0392B"
  },
  {
    id: 10,
    name: "Verbier",
    nameZh: "韦尔比耶",
    region: "瑞士",
    country: "Switzerland",
    difficulty: "expert",
    trails: "210+条雪道",
    vertical: "1,800m落差",
    season: "11月-4月",
    snowfall: "年均7m",
    highlights: "韦尔比耶是自由式滑雪的圣地，以陡峭的野雪路线和极限地形闻名于世。Mont Fort峰顶海拔3,330米，提供壮观的阿尔卑斯全景。国际化的氛围和活跃的夜生活使其成为欧洲最时尚的滑雪目的地之一。",
    tips: "Mont Fort缆车仅限高级滑雪者；Freeride World Tour常在此举办，赛事期间一票难求。",
    color: "#D94F4F"
  },
  {
    id: 11,
    name: "St. Moritz",
    nameZh: "圣莫里茨",
    region: "瑞士",
    country: "Switzerland",
    difficulty: "intermediate",
    trails: "160+条雪道",
    vertical: "1,748m落差",
    season: "11月-4月",
    snowfall: "年均5m",
    highlights: "圣莫里茨是冬季旅游的发源地，曾两次举办冬奥会，拥有超过150年的滑雪历史。海拔1,800米的恩加丁山谷阳光充沛，年均晴天超过300天。冰湖赛马和雪地马球等独特活动彰显其奢华定位。",
    tips: "持滑雪通票可乘坐冰川快车等景观列车；建议体验Corviglia雪场的湖景雪道。",
    color: "#E76F6F"
  },
  {
    id: 12,
    name: "St. Anton am Arlberg",
    nameZh: "圣安东",
    region: "奥地利",
    country: "Austria",
    difficulty: "advanced",
    trails: "300+条雪道",
    vertical: "1,507m落差",
    season: "12月-4月",
    snowfall: "年均7m",
    highlights: "圣安东是阿尔卑斯滑雪的发源地之一，以充满挑战的地形和传奇的派对文化闻名。阿尔贝格滑雪区是奥地利最大的相连滑雪区域，覆盖300多公里雪道。丰富的野雪路线和陡峭的雪沟是高级滑雪者的天堂。",
    tips: "Mooserwirt被称为「全球最疯狂的après-ski酒吧」，下午茶时段不容错过。",
    color: "#E8A838"
  },
  {
    id: 13,
    name: "Kitzbühel",
    nameZh: "基茨比厄尔",
    region: "奥地利",
    country: "Austria",
    difficulty: "advanced",
    trails: "170+条雪道",
    vertical: "1,200m落差",
    season: "10月-4月",
    snowfall: "年均5m",
    highlights: "基茨比厄尔是中世纪风情小镇与世界级滑雪的完美结合。Hahnenkamm下坡赛是高山滑雪世界杯最具传奇色彩的赛事，Streif赛道坡度达85%。800年历史的老城区色彩缤纷，充满蒂罗尔传统魅力。",
    tips: "每年1月Hahnenkamm赛事期间住宿紧张且价格翻倍，建议错峰前往或提前半年预订。",
    color: "#F0B848"
  },
  {
    id: 14,
    name: "Jackson Hole",
    nameZh: "杰克逊霍尔",
    region: "美国",
    country: "USA",
    difficulty: "expert",
    trails: "130+条雪道",
    vertical: "1,262m落差",
    season: "12月-4月",
    snowfall: "年均12m",
    highlights: "杰克逊霍尔以北美最陡峭的地形和传奇的Corbet's Couloir闻名，是极限滑雪者的朝圣地。雪场50%的雪道为专家级，空中缆车直达山顶的体验无与伦比。毗邻大提顿和黄石国家公园，自然风光震撼人心。",
    tips: "Corbet's Couloir入口需跳崖进入，仅限专家级滑雪者；镇上广场的鹿角拱门是经典打卡点。",
    color: "#2C5F2D"
  },
  {
    id: 15,
    name: "Aspen Snowmass",
    nameZh: "阿斯本",
    region: "美国",
    country: "USA",
    difficulty: "intermediate",
    trails: "330+条雪道",
    vertical: "1,343m落差",
    season: "11月-4月",
    snowfall: "年均8m",
    highlights: "阿斯本是美国最具标志性的滑雪度假地，四座雪场各具特色。集世界级滑雪、顶级美食、艺术画廊和名品购物于一体。X Games极限运动赛事每年在此举办，吸引全球目光。",
    tips: "四座雪场用一张票通滑；推荐Snowmass适合家庭，Highlands的Highland Bowl适合高手。",
    color: "#3D7A3E"
  },
  {
    id: 16,
    name: "Mammoth Mountain",
    nameZh: "猛犸山",
    region: "美国",
    country: "USA",
    difficulty: "intermediate",
    trails: "150+条雪道",
    vertical: "953m落差",
    season: "11月-6月",
    snowfall: "年均10m",
    highlights: "猛犸山拥有加州最大的滑雪区域和超长的雪季，常滑至来年6月。海拔3,369米的山顶提供内华达山脉的壮丽全景。距离洛杉矶仅5小时车程，是加州滑雪者的首选目的地。",
    tips: "从洛杉矶自驾走395号公路沿途风景绝美；山顶风大体感温度极低，注意防风保暖。",
    color: "#4E8B4F"
  },
  {
    id: 17,
    name: "Park City",
    nameZh: "帕克城",
    region: "美国",
    country: "USA",
    difficulty: "beginner",
    trails: "330+条雪道",
    vertical: "953m落差",
    season: "11月-4月",
    snowfall: "年均9m",
    highlights: "帕克城是美国最大的单体滑雪场，2002年冬奥会举办地。与鹿谷度假村合并后雪道总长超过7,300英亩，适合各级滑雪者。历史悠久的主街餐厅酒吧林立，圣丹斯电影节也在此举办。",
    tips: "从盐湖城机场仅40分钟车程，是美国最便捷的滑雪目的地之一。",
    color: "#5F9C60"
  },
  {
    id: 18,
    name: "Whistler Blackcomb",
    nameZh: "惠斯勒黑梳山",
    region: "加拿大",
    country: "Canada",
    difficulty: "advanced",
    trails: "200+条雪道",
    vertical: "1,609m落差",
    season: "11月-5月",
    snowfall: "年均12m",
    highlights: "惠斯勒是北美最大的滑雪度假村，2010年冬奥会举办地。Peak 2 Peak缆车连接两座山峰，是世界上跨度最长的无支撑缆车。度假村设施完善，餐饮娱乐选择丰富，是北美滑雪的终极体验。",
    tips: "Peak 2 Peak缆车底部透明舱位需排队，建议工作日上午体验；从温哥华走海天公路约2小时。",
    color: "#8B0000"
  },
  {
    id: 19,
    name: "Revelstoke",
    nameZh: "雷夫尔斯托克",
    region: "加拿大",
    country: "Canada",
    difficulty: "expert",
    trails: "75+条雪道",
    vertical: "1,713m落差",
    season: "12月-4月",
    snowfall: "年均12m",
    highlights: "雷夫尔斯托克拥有北美最大的垂直落差，深粉雪和树林滑雪是其招牌。相比其他大型度假村游客较少，能享受到真正的「粉雪日」体验。直升机滑雪和雪猫滑雪项目也是当地特色。",
    tips: "雪场规模不断扩张中，部分区域需具备野雪经验；镇上住宿性价比高于山上酒店。",
    color: "#A52A2A"
  },
  {
    id: 20,
    name: "Banff Sunshine & Lake Louise",
    nameZh: "班夫阳光村与路易斯湖",
    region: "加拿大",
    country: "Canada",
    difficulty: "intermediate",
    trails: "260+条雪道",
    vertical: "1,000m落差",
    season: "11月-5月",
    snowfall: "年均9m",
    highlights: "班夫国家公园内的两座世界级雪场，被壮丽的加拿大落基山脉环绕。路易斯湖雪场拥有令人屏息的山谷景观，阳光村则以超长雪季和天然干粉雪著称。野生动物时常出没于雪道周边，自然体验独一无二。",
    tips: "Tri-Area联票可通滑三个雪场含Mt. Norquay；班夫镇到雪场有免费穿梭巴士。",
    color: "#BF3636"
  },
  {
    id: 21,
    name: "Queenstown (Remarkables & Coronet Peak)",
    nameZh: "皇后镇",
    region: "新西兰",
    country: "New Zealand",
    difficulty: "intermediate",
    trails: "50+条雪道",
    vertical: "468m落差",
    season: "6月-10月",
    snowfall: "年均4m",
    highlights: "皇后镇是南半球最受欢迎的滑雪目的地，坐拥瓦卡蒂普湖和卓越山脉的绝美景色。两座雪场风格各异，Coronet Peak提供夜场滑雪，Remarkables地形更具挑战性。冬季蹦极、喷射快艇等极限活动同样精彩。",
    tips: "南半球雪季为6-10月，适合北半球滑雪者「追雪」；持多日票可两座雪场通滑。",
    color: "#1ABC9C"
  },
  {
    id: 22,
    name: "Cortina d'Ampezzo",
    nameZh: "科尔蒂纳丹佩佐",
    region: "意大利",
    country: "Italy",
    difficulty: "intermediate",
    trails: "120+条雪道",
    vertical: "1,400m落差",
    season: "12月-4月",
    snowfall: "年均5m",
    highlights: "科尔蒂纳是意大利多洛米蒂山脉的皇冠明珠，2026年冬奥会联合举办地。壮观的白云石峰林造就了全球最美的滑雪风景。Sella Ronda环线是阿尔卑斯最经典的滑雪线路之一，意式美食更是锦上添花。",
    tips: "Dolomiti Superski超级雪票覆盖1,200公里雪道；Sella Ronda环线建议顺时针方向滑行更流畅。",
    color: "#27AE60"
  },
  {
    id: 23,
    name: "Lofoten",
    nameZh: "罗弗敦群岛",
    region: "挪威",
    country: "Norway",
    difficulty: "expert",
    trails: "野雪为主",
    vertical: "1,000m落差",
    season: "2月-5月",
    snowfall: "年均3m",
    highlights: "罗弗敦提供全球最独特的滑雪体验——从雪山山顶直滑入北极圈的峡湾海面。没有缆车和雪道标记，完全依靠登山滑雪（ski touring）到达山顶。北极光与午夜阳光交替的奇幻光线条件令人陶醉。",
    tips: "必须具备丰富的登山滑雪和雪崩安全知识；建议聘请当地向导并携带全套安全装备。",
    color: "#2980B9"
  },
  {
    id: 24,
    name: "Portillo",
    nameZh: "波蒂略",
    region: "智利",
    country: "Chile",
    difficulty: "advanced",
    trails: "35+条雪道",
    vertical: "800m落差",
    season: "6月-10月",
    snowfall: "年均7m",
    highlights: "波蒂略是南美洲最传奇的滑雪胜地，坐落于安第斯山脉海拔2,880米处。度假村仅有一家酒店，每日限流450人，营造出极致私密的滑雪体验。因干燥气候产生的安第斯粉雪品质卓越，曾是多项速度滑雪世界纪录的诞生地。",
    tips: "住宿需提前数月预订且通常为一周套餐制；从圣地亚哥驱车约2.5小时可达。",
    color: "#8E44AD"
  },
  {
    id: 25,
    name: "Cervinia (Breuil-Cervinia)",
    nameZh: "切尔维尼亚",
    region: "意大利",
    country: "Italy",
    difficulty: "beginner",
    trails: "150+条雪道",
    vertical: "2,050m落差",
    season: "10月-5月",
    snowfall: "年均6m",
    highlights: "切尔维尼亚位于马特洪峰意大利一侧，与瑞士采尔马特共享滑雪区域，构成欧洲最高的滑雪天堂。宽阔平缓的雪道非常适合初中级滑雪者，雪季超长可从秋季滑至来年春末。意大利一侧的价格比瑞士更亲民，美食也更地道。",
    tips: "持国际联票可跨境滑至采尔马特；山顶Plateau Rosa海拔3,480m，注意高反和防晒。",
    color: "#9B59B6"
  }
];

const SKI_REGION_EMOJI = {
  "日本": "🇯🇵",
  "法国": "🇫🇷",
  "美国": "🇺🇸",
  "瑞士": "🇨🇭",
  "加拿大": "🇨🇦",
  "奥地利": "🇦🇹",
  "意大利": "🇮🇹",
  "新西兰": "🇳🇿",
  "挪威": "🇳🇴",
  "智利": "🇨🇱"
};

const SKI_DIFFICULTY_LABELS = {
  beginner: "初学者友好",
  intermediate: "中级",
  advanced: "高级",
  expert: "专家级"
};
