const SURF_SPOTS = [
  {
    id: 1,
    name: "Pipeline",
    nameZh: "管道",
    region: "美国",
    country: "Hawaii, USA",
    difficulty: "expert",
    waveType: "管浪/reef break",
    bestSeason: "11月-2月",
    waterTemp: "24-27°C",
    highlights: "北岸最具标志性的浪点，以完美的管状浪闻名于世。每年冬季吸引全球顶尖冲浪者前来挑战，是世界冲浪锦标赛的经典赛场。浅礁底质造就了力量惊人的空心浪壁。",
    tips: "仅限经验丰富的冲浪者，注意浅礁和强劲水流，建议提前观察浪况并与当地人沟通。",
    color: "#E74C3C"
  },
  {
    id: 2,
    name: "Mavericks",
    nameZh: "独行侠",
    region: "美国",
    country: "California, USA",
    difficulty: "expert",
    waveType: "大浪/point break",
    bestSeason: "10月-3月",
    waterTemp: "10-14°C",
    highlights: "加州半月湾附近的传奇大浪浪点，浪高可达18米以上。冰冷的水温和凶猛的浪涌让这里成为大浪冲浪的终极试炼场。周边还有大白鲨出没，极具冒险色彩。",
    tips: "必须穿厚款湿衣（5/4mm），仅限大浪专家，建议有水上摩托救援支持。",
    color: "#2C3E50"
  },
  {
    id: 3,
    name: "Rincon",
    nameZh: "林孔",
    region: "美国",
    country: "California, USA",
    difficulty: "intermediate",
    waveType: "长浪/point break",
    bestSeason: "10月-4月",
    waterTemp: "13-18°C",
    highlights: "被誉为「加州冲浪皇后」，以超长且优雅的右手浪著称。完美的浪壁适合各种风格的冲浪，从长板到短板都能找到乐趣。冬季涌浪季节浪况最佳。",
    tips: "停车位有限建议早到，尊重当地冲浪礼仪，冬季需准备3/2mm湿衣。",
    color: "#F39C12"
  },
  {
    id: 4,
    name: "Trestles",
    nameZh: "特雷斯特尔斯",
    region: "美国",
    country: "California, USA",
    difficulty: "intermediate",
    waveType: "沙底/beach break & cobblestone",
    bestSeason: "4月-10月",
    waterTemp: "15-21°C",
    highlights: "位于圣克莱门特的世界级高性能浪点，WSL巡回赛固定赛场。浪型多变且力量充沛，适合各类技术动作的练习。需徒步约20分钟穿过自然保护区才能到达。",
    tips: "需从停车场步行进入，带足饮水和防晒，南涌浪和西北涌浪均可冲。",
    color: "#3498DB"
  },
  {
    id: 5,
    name: "Huntington Beach",
    nameZh: "亨廷顿海滩",
    region: "美国",
    country: "California, USA",
    difficulty: "beginner",
    waveType: "沙底/beach break",
    bestSeason: "全年",
    waterTemp: "14-21°C",
    highlights: "自称「冲浪之城」，是美国冲浪文化的发源地之一。码头两侧提供稳定的浪况，适合各级别冲浪者。每年举办US Open of Surfing，冲浪氛围浓厚。",
    tips: "码头南侧适合初学者，北侧浪更有力；周末人多建议平日前往，附近有大量冲浪用品店。",
    color: "#E67E22"
  },
  {
    id: 6,
    name: "Gold Coast",
    nameZh: "黄金海岸",
    region: "澳大利亚",
    country: "Australia",
    difficulty: "intermediate",
    waveType: "沙底/point break",
    bestSeason: "2月-5月",
    waterTemp: "20-27°C",
    highlights: "澳大利亚冲浪圣地，Snapper Rocks到Kirra的超级沙滩提供连绵不断的优质浪点。飓风涌浪季节可产生长达数百米的完美右手浪。冲浪产业和文化高度发达。",
    tips: "Snapper Rocks人多且竞争激烈，可尝试附近Duranbah或Currumbin等浪点分散人流。",
    color: "#F1C40F"
  },
  {
    id: 7,
    name: "Bells Beach",
    nameZh: "贝尔斯海滩",
    region: "澳大利亚",
    country: "Australia",
    difficulty: "advanced",
    waveType: "礁石/reef break",
    bestSeason: "3月-6月",
    waterTemp: "13-18°C",
    highlights: "维多利亚州的传奇浪点，自1962年起举办Rip Curl Pro赛事，是世界上历史最悠久的冲浪比赛场地。强劲的南大洋涌浪造就了有力的右手浪壁，考验冲浪者的力量型转向。",
    tips: "水温较低需4/3mm湿衣，停车场到海滩有陡峭阶梯，注意岩石区域。",
    color: "#1ABC9C"
  },
  {
    id: 8,
    name: "Margaret River",
    nameZh: "玛格丽特河",
    region: "澳大利亚",
    country: "Australia",
    difficulty: "advanced",
    waveType: "礁石/reef break",
    bestSeason: "4月-9月",
    waterTemp: "16-21°C",
    highlights: "西澳大利亚最著名的大浪冲浪区域，拥有多个世界级浪点。The Box以其猛烈的空心浪而闻名，Main Break则是WSL巡回赛举办地。同时也是知名葡萄酒产区，冲浪后可品酒放松。",
    tips: "鲨鱼活动频繁，建议使用防鲨设备并结伴冲浪，冬季需准备厚湿衣。",
    color: "#8E44AD"
  },
  {
    id: 9,
    name: "Uluwatu",
    nameZh: "乌鲁瓦图",
    region: "印尼",
    country: "Indonesia",
    difficulty: "advanced",
    waveType: "礁石/reef break",
    bestSeason: "4月-10月",
    waterTemp: "27-29°C",
    highlights: "巴厘岛最负盛名的浪点，悬崖下的蔚蓝海水中涌起完美的左手管浪。日落时分的冲浪体验堪称世界一绝，金色阳光洒在浪壁上如梦似幻。洞穴入口增添了探险的仪式感。",
    tips: "通过悬崖洞穴下水，注意潮汐变化；低潮时礁石暴露危险，建议中高潮冲浪。",
    color: "#16A085"
  },
  {
    id: 10,
    name: "G-Land",
    nameZh: "G-兰德",
    region: "印尼",
    country: "Indonesia",
    difficulty: "expert",
    waveType: "管浪/reef break",
    bestSeason: "4月-10月",
    waterTemp: "26-29°C",
    highlights: "爪哇岛东南角隐藏在丛林中的传奇浪点，被誉为世界上最长最完美的左手管浪之一。远离城市的原始环境让冲浪回归纯粹，需乘船或穿越丛林才能抵达。浪高可达4-6米。",
    tips: "需提前预订冲浪营地，带足防蚊用品和常用药物，最近的医院在数小时车程之外。",
    color: "#27AE60"
  },
  {
    id: 11,
    name: "Mentawai Islands",
    nameZh: "明打威群岛",
    region: "印尼",
    country: "Indonesia",
    difficulty: "advanced",
    waveType: "管浪/reef break",
    bestSeason: "3月-11月",
    waterTemp: "28-30°C",
    highlights: "拥有数十个世界级浪点的热带群岛天堂，包括Lance's Right、Macaronis等传奇波浪。温暖清澈的海水配合完美的管浪，是冲浪者的终极梦想目的地。通常需乘坐冲浪船旅行数日。",
    tips: "推荐冲浪船之旅（charter boat），自带急救包和备用板，尊重当地土著文化。",
    color: "#2ECC71"
  },
  {
    id: 12,
    name: "Waikiki",
    nameZh: "威基基",
    region: "美国",
    country: "Hawaii, USA",
    difficulty: "beginner",
    waveType: "长浪/reef break",
    bestSeason: "全年（夏季最佳）",
    waterTemp: "24-27°C",
    highlights: "现代冲浪运动的诞生地，Duke Kahanamoku在此将冲浪推向世界。温和的长浪和温暖的海水让这里成为初学者的天堂。在钻石头山的壮丽背景下冲浪，体验纯正的阿罗哈精神。",
    tips: "冲浪板和课程租赁充足，注意避让独木舟和其他水上活动者，防晒必不可少。",
    color: "#FF6B81"
  },
  {
    id: 13,
    name: "Jaws (Pe'ahi)",
    nameZh: "大白鲨浪点",
    region: "美国",
    country: "Hawaii, USA",
    difficulty: "expert",
    waveType: "大浪/reef break",
    bestSeason: "11月-3月",
    waterTemp: "23-26°C",
    highlights: "毛伊岛北岸的超级大浪浪点，浪高可达20米以上，是全球拖曳冲浪的圣地。巨浪如同移动的山脉般壮观，仅有少数顶尖大浪冲浪者敢于挑战。岸上观景台可近距离感受震撼。",
    tips: "仅限职业大浪冲浪者且需水上摩托支援，普通冲浪者可在岸上观赏这一自然奇观。",
    color: "#C0392B"
  },
  {
    id: 14,
    name: "Nazaré",
    nameZh: "纳扎雷",
    region: "葡萄牙",
    country: "Portugal",
    difficulty: "expert",
    waveType: "大浪/beach break",
    bestSeason: "10月-3月",
    waterTemp: "13-18°C",
    highlights: "世界纪录级别的超级大浪浪点，海底峡谷将大西洋涌浪放大至30米高度。这里打破了多项大浪冲浪世界纪录，灯塔是标志性的观浪地标。小镇渔村氛围与壮观巨浪形成强烈反差。",
    tips: "灯塔观景台免费开放，冬季风大注意保暖；大浪日仅限有资质的职业选手下水。",
    color: "#9B59B6"
  },
  {
    id: 15,
    name: "Peniche",
    nameZh: "佩尼什",
    region: "葡萄牙",
    country: "Portugal",
    difficulty: "intermediate",
    waveType: "沙底/beach break",
    bestSeason: "9月-4月",
    waterTemp: "14-20°C",
    highlights: "半岛地形让Peniche几乎在任何风向下都有可冲的浪，其中Supertubos以强力管浪享誉世界。WSL巡回赛固定举办地，也是欧洲冲浪培训的重要基地。性价比极高的冲浪度假目的地。",
    tips: "Supertubos适合进阶者，初学者可选择Baleal附近更温和的浪点，水温偏凉需带湿衣。",
    color: "#2980B9"
  },
  {
    id: 16,
    name: "Hossegor",
    nameZh: "奥塞戈尔",
    region: "法国",
    country: "France",
    difficulty: "advanced",
    waveType: "沙底/beach break",
    bestSeason: "9月-11月",
    waterTemp: "15-22°C",
    highlights: "欧洲冲浪之都，La Gravière沙滩以产出媲美夏威夷的管浪而闻名。独特的海底沙坝地形每年变化，创造出不可预测但极其强劲的空心浪。秋季是最佳季节，浪大且水温尚可。",
    tips: "沙坝位置每年变化需观察地形，秋季最佳；La Gravière水流强劲，中级者选La Nord更安全。",
    color: "#34495E"
  },
  {
    id: 17,
    name: "Mundaka",
    nameZh: "蒙达卡",
    region: "西班牙",
    country: "Spain",
    difficulty: "advanced",
    waveType: "河口/rivermouth break",
    bestSeason: "9月-3月",
    waterTemp: "12-20°C",
    highlights: "巴斯克地区的宝藏浪点，河口地形产生欧洲最长最完美的左手管浪。当条件完美时浪可连续剥离200多米，被公认为欧洲最佳浪点之一。小镇古朴迷人，巴斯克美食享誉全球。",
    tips: "浪况依赖特定涌浪方向和沙坝条件，可能数周没有好浪；提前关注预报，备选附近Bakio等浪点。",
    color: "#D35400"
  },
  {
    id: 18,
    name: "Jeffreys Bay",
    nameZh: "杰弗里斯湾",
    region: "南非",
    country: "South Africa",
    difficulty: "advanced",
    waveType: "长浪/point break",
    bestSeason: "5月-9月",
    waterTemp: "14-20°C",
    highlights: "世界上最完美的右手point break之一，Supertubes段的浪壁机械般精准有力。完美条件下可以从Boneyards一直冲到Impossibles，全长超过800米。WSL巡回赛经典站点。",
    tips: "水温偏凉建议4/3mm湿衣，注意当地冲浪秩序（localism较强），鲨鱼防护设备推荐使用。",
    color: "#1E8449"
  },
  {
    id: 19,
    name: "Taghazout",
    nameZh: "塔格哈祖特",
    region: "摩洛哥",
    country: "Morocco",
    difficulty: "intermediate",
    waveType: "礁石/point break",
    bestSeason: "10月-4月",
    waterTemp: "16-22°C",
    highlights: "北非最受欢迎的冲浪小镇，Anchor Point等浪点提供优质的右手point break。大西洋涌浪配合温和的气候，吸引大量欧洲冲浪者在冬季前来避寒冲浪。摩洛哥文化体验丰富多彩。",
    tips: "尊重当地穆斯林文化习俗，斋月期间注意公共场合饮食；冬季早晚温差大备好保暖衣物。",
    color: "#E59866"
  },
  {
    id: 20,
    name: "Shonan",
    nameZh: "湘南",
    region: "日本",
    country: "Japan",
    difficulty: "beginner",
    waveType: "沙底/beach break",
    bestSeason: "8月-11月（台风季）",
    waterTemp: "16-26°C",
    highlights: "距东京最近的冲浪海岸，是日本冲浪文化的中心。在富士山和江之岛的背景下冲浪别有一番风味。台风季节偶有优质浪况，平日浪小适合初学者练习。冲浪与日式海边生活完美融合。",
    tips: "平日浪较小适合练习，台风前后有惊喜好浪；电车可达非常方便，周末极其拥挤。",
    color: "#FF7979"
  },
  {
    id: 21,
    name: "Chiba",
    nameZh: "千叶",
    region: "日本",
    country: "Japan",
    difficulty: "intermediate",
    waveType: "沙底/beach break",
    bestSeason: "9月-11月",
    waterTemp: "15-26°C",
    highlights: "2020东京奥运会冲浪比赛场地，志田下等浪点在日本冲浪界享有盛名。太平洋涌浪直接到达，浪况比湘南更加稳定和有力。是东京冲浪者周末的首选目的地。",
    tips: "从东京开车约1.5小时，停车场需提前到达；台风季注意安全预警，当地冲浪店可获取实时浪报。",
    color: "#6C5CE7"
  },
  {
    id: 22,
    name: "Arugam Bay",
    nameZh: "阿鲁甘湾",
    region: "斯里兰卡",
    country: "Sri Lanka",
    difficulty: "intermediate",
    waveType: "礁石/point break",
    bestSeason: "4月-10月",
    waterTemp: "27-30°C",
    highlights: "斯里兰卡东海岸的冲浪天堂，以温暖的海水和悠闲的热带氛围著称。Main Point提供稳定的右手浪，适合中级冲浪者进阶。物价低廉，是长期冲浪旅行者的理想驻扎地。",
    tips: "4-9月为旱季最佳时段，住宿简朴但性价比极高；注意防晒和补水，周边可游览野生动物保护区。",
    color: "#00B894"
  },
  {
    id: 23,
    name: "Puerto Escondido",
    nameZh: "埃斯孔迪多港",
    region: "墨西哥",
    country: "Mexico",
    difficulty: "expert",
    waveType: "管浪/beach break",
    bestSeason: "5月-9月",
    waterTemp: "26-30°C",
    highlights: "被称为「墨西哥管道」，Zicatela海滩以极其猛烈的岸break管浪闻名。砂底却能产生比肩礁石浪点的管状浪，wipeout的力量令人敬畏。也是性价比极高的冲浪度假地。",
    tips: "Zicatela仅限高手，初中级者选La Punta或Carrizalillo更安全；注意强烈岸流，保持体力储备。",
    color: "#D63031"
  },
  {
    id: 24,
    name: "Teahupo'o",
    nameZh: "提阿胡普",
    region: "塔希提",
    country: "Tahiti, French Polynesia",
    difficulty: "expert",
    waveType: "管浪/reef break",
    bestSeason: "5月-10月",
    waterTemp: "26-29°C",
    highlights: "世界上最重最危险的浪之一，浅礁上涌起的厚重管浪如同液体大教堂。2024巴黎奥运会冲浪项目举办地，将这个南太平洋秘境推上世界舞台。浪壁之厚重和完美令人叹为观止。",
    tips: "绝对仅限职业级冲浪者，需乘船到达浪点；观看可乘小船在水道安全位置欣赏，切勿低估其危险性。",
    color: "#6F1E51"
  },
  {
    id: 25,
    name: "Santa Teresa",
    nameZh: "圣特雷莎",
    region: "哥斯达黎加",
    country: "Costa Rica",
    difficulty: "beginner",
    waveType: "沙底/beach break",
    bestSeason: "12月-4月",
    waterTemp: "27-30°C",
    highlights: "哥斯达黎加太平洋海岸的冲浪伊甸园，温暖的海水和稳定的浪况全年友好。Playa Hermosa和Playa Carmen提供多样的浪型选择。瑜伽、冲浪和热带丛林的完美结合。",
    tips: "旱季12-4月最佳，雨季下午多雷阵雨但早晨依然可冲；蚊虫较多备好驱蚊液，体验当地Pura Vida生活方式。",
    color: "#00CEC9"
  },
  {
    id: 26,
    name: "Cloudbreak",
    nameZh: "云破浪点",
    region: "斐济",
    country: "Fiji",
    difficulty: "expert",
    waveType: "管浪/reef break",
    bestSeason: "5月-10月",
    waterTemp: "25-28°C",
    highlights: "南太平洋最负盛名的浪点，距离Tavarua岛不远的外礁产出完美且力量惊人的左手管浪。碧蓝透明的热带海水中，浪壁如水晶般剔透。大涌浪日可产出6米以上的完美管浪。",
    tips: "需通过船只到达，建议预订度假村套餐含船接送；珊瑚礁锋利务必穿礁鞋，携带足够防晒。",
    color: "#0984E3"
  }
];

const SURF_REGION_EMOJI = {
  "美国": "🇺🇸",
  "澳大利亚": "🇦🇺",
  "印尼": "🇮🇩",
  "日本": "🇯🇵",
  "葡萄牙": "🇵🇹",
  "南非": "🇿🇦",
  "法国": "🇫🇷",
  "摩洛哥": "🇲🇦",
  "斯里兰卡": "🇱🇰",
  "西班牙": "🇪🇸",
  "墨西哥": "🇲🇽",
  "塔希提": "🇵🇫",
  "哥斯达黎加": "🇨🇷",
  "斐济": "🇫🇯"
};

const SURF_DIFFICULTY_LABELS = {
  beginner: "适合初学",
  intermediate: "中级",
  advanced: "高级",
  expert: "大浪猎人"
};
