const TEAS = [
  {
    id: 1,
    name: "Longjing (Dragon Well)",
    nameZh: "龙井",
    category: "green",
    origin: "中国浙江·杭州西湖",
    brewTemp: "80-85°C",
    brewTime: "2-3分钟",
    caffeine: "medium",
    flavor: ["豆香", "栗香", "清甜", "回甘"],
    highlights: "龙井茶是中国十大名茶之首，产于杭州西湖一带，已有一千多年历史。茶叶扁平光滑，色泽翠绿，冲泡后香气清高持久，滋味甘醇鲜爽。乾隆皇帝曾六下江南品饮龙井，御封'十八棵御茶'至今仍存。",
    tips: "建议用玻璃杯冲泡，水温不宜过高，80°C左右最佳，可观赏茶叶在杯中上下翻飞的优美姿态。",
    color: "#a8d86e"
  },
  {
    id: 2,
    name: "Biluochun",
    nameZh: "碧螺春",
    category: "green",
    origin: "中国江苏·苏州太湖洞庭山",
    brewTemp: "75-80°C",
    brewTime: "1-2分钟",
    caffeine: "medium",
    flavor: ["花果香", "鲜爽", "清甜", "嫩香"],
    highlights: "碧螺春产于太湖洞庭山，因其卷曲如螺、色泽碧绿而得名。春分前后采摘，一斤干茶需六万余个嫩芽。汤色碧绿清澈，入口鲜爽回甘，带有天然的花果香气，被誉为'吓煞人香'。",
    tips: "宜采用上投法冲泡：先注水再投茶，让茶叶缓缓下沉，避免高温破坏嫩芽的鲜爽口感。",
    color: "#b5d96c"
  },
  {
    id: 3,
    name: "Huangshan Maofeng",
    nameZh: "黄山毛峰",
    category: "green",
    origin: "中国安徽·黄山",
    brewTemp: "80-85°C",
    brewTime: "2-3分钟",
    caffeine: "medium",
    flavor: ["兰花香", "清鲜", "甘润", "高山韵"],
    highlights: "黄山毛峰产于安徽黄山风景区，海拔高、云雾多，茶叶品质极优。外形微卷似雀舌，白毫显露，冲泡后兰花香气馥郁。作为中国十大名茶之一，其'鱼叶金黄'是辨别正宗的重要标志。",
    tips: "冲泡时水温控制在80-85°C，第一泡浸润30秒即可出汤，后续每泡可适当延长时间。",
    color: "#c5e07a"
  },
  {
    id: 4,
    name: "Taiping Houkui",
    nameZh: "太平猴魁",
    category: "green",
    origin: "中国安徽·黄山太平",
    brewTemp: "85-90°C",
    brewTime: "3-5分钟",
    caffeine: "medium",
    flavor: ["兰花香", "醇厚", "回甘", "清爽"],
    highlights: "太平猴魁是中国绿茶中外形最独特的品种，两叶抱一芽，叶片长达5-7厘米，扁平挺直如刀剑。产于黄山市猴坑一带，1915年曾获巴拿马万国博览会金奖。滋味醇厚甘甜，兰香持久不散。",
    tips: "建议用直筒玻璃杯冲泡，将茶叶根部朝下竖直放入杯中，缓慢注水，可欣赏叶片舒展的壮观景象。",
    color: "#a9c96a"
  },
  {
    id: 5,
    name: "Keemun Black Tea",
    nameZh: "祁门红茶",
    category: "black",
    origin: "中国安徽·祁门",
    brewTemp: "90-95°C",
    brewTime: "3-5分钟",
    caffeine: "high",
    flavor: ["祁门香", "蜜糖香", "果香", "醇厚"],
    highlights: "祁门红茶被誉为'红茶皇后'，与印度大吉岭、斯里兰卡乌巴并称世界三大高香红茶。其独特的'祁门香'似花似果似蜜，曾是英国王室的御用茶品。汤色红艳明亮，口感醇厚细腻，回味悠长。",
    tips: "用95°C左右热水冲泡，前三泡控制在30-45秒，可加少许牛奶调饮，风味更加丰富迷人。",
    color: "#c4503a"
  },
  {
    id: 6,
    name: "Lapsang Souchong",
    nameZh: "正山小种",
    category: "black",
    origin: "中国福建·武夷山桐木关",
    brewTemp: "90-95°C",
    brewTime: "3-4分钟",
    caffeine: "high",
    flavor: ["松烟香", "桂圆香", "甘甜", "醇滑"],
    highlights: "正山小种是世界红茶鼻祖，诞生于福建武夷山桐木关，已有四百余年历史。传统工艺采用松木熏焙，赋予茶叶独特的松烟香和桂圆甜味。17世纪传入英国后，开启了欧洲饮红茶的风潮。",
    tips: "水温宜高，95°C冲泡最能释放其松烟香韵。第一泡快速出汤洗茶，从第二泡开始品饮效果最佳。",
    color: "#b5422e"
  },
  {
    id: 7,
    name: "Dian Hong",
    nameZh: "滇红",
    category: "black",
    origin: "中国云南·临沧凤庆",
    brewTemp: "85-90°C",
    brewTime: "3-5分钟",
    caffeine: "high",
    flavor: ["蜜香", "焦糖香", "浓醇", "甘甜"],
    highlights: "滇红产于云南，以大叶种茶为原料制成，金毫显露，汤色红浓透亮。因云南高海拔独特气候，茶叶内含物丰富，口感浓强饱满却不苦涩。其中'金芽滇红'更是以满身金毫、蜜香浓郁著称。",
    tips: "水温不宜过高，85-90°C为佳，过高会带出苦涩味。快速出汤可品其甜润，慢泡则享其醇厚。",
    color: "#d4633e"
  },
  {
    id: 8,
    name: "Tieguanyin",
    nameZh: "铁观音",
    category: "oolong",
    origin: "中国福建·安溪",
    brewTemp: "95-100°C",
    brewTime: "1-2分钟",
    caffeine: "medium",
    flavor: ["兰花香", "观音韵", "回甘", "清幽"],
    highlights: "铁观音是中国乌龙茶的代表，产于福建安溪，以'观音韵、兰花香'闻名天下。茶叶呈颗粒状卷曲，冲泡后叶底肥厚油亮。清香型铁观音鲜爽怡人，浓香型则醇厚甘滑，素有'七泡有余香'之美誉。",
    tips: "功夫茶泡法最佳：用紫砂壶或盖碗，沸水冲泡，快速出汤。每泡间隔不宜过长，可连续冲泡七八次。",
    color: "#d4b84a"
  },
  {
    id: 9,
    name: "Da Hong Pao",
    nameZh: "大红袍",
    category: "oolong",
    origin: "中国福建·武夷山",
    brewTemp: "95-100°C",
    brewTime: "1-3分钟",
    caffeine: "medium",
    flavor: ["岩骨花香", "焙火香", "醇厚", "回甘绵长"],
    highlights: "大红袍是武夷岩茶之王，生长于武夷山九龙窠的悬崖峭壁上，母树仅存六棵，堪称茶中极品。其'岩骨花香'的独特韵味源于丹霞地貌的岩石土壤。经炭火慢焙而成，滋味醇厚饱满，岩韵悠长。",
    tips: "沸水冲泡，首泡洗茶后弃去。品饮时先闻杯底香，再小口啜饮，感受'岩骨花香'的层次变化。",
    color: "#c47a28"
  },
  {
    id: 10,
    name: "Phoenix Dancong",
    nameZh: "凤凰单丛",
    category: "oolong",
    origin: "中国广东·潮州凤凰山",
    brewTemp: "95-100°C",
    brewTime: "1-2分钟",
    caffeine: "medium",
    flavor: ["天然花香", "蜜韵", "山韵", "回甘"],
    highlights: "凤凰单丛产于广东潮州凤凰山，以一树一香闻名，有蜜兰香、鸭屎香、芝兰香等十大香型。每棵古茶树都有独特的香气个性，单独采制，故名'单丛'。茶汤金黄明亮，香气馥郁高扬，层次丰富多变。",
    tips: "潮州功夫茶泡法：小壶小杯，沸水快冲快出，每泡不超过15秒。关公巡城、韩信点兵手法倒茶最为正宗。",
    color: "#d9a83c"
  },
  {
    id: 11,
    name: "Oriental Beauty",
    nameZh: "东方美人",
    category: "oolong",
    origin: "中国台湾·新竹北埔",
    brewTemp: "85-90°C",
    brewTime: "2-3分钟",
    caffeine: "medium",
    flavor: ["蜜香", "果香", "熟果甜", "柔滑"],
    highlights: "东方美人又称膨风茶、白毫乌龙，是全世界发酵度最高的乌龙茶。其独特蜜香来自小绿叶蝉的叮咬，必须在完全不使用农药的环境下才能生产。英国维多利亚女王品尝后赞不绝口，赐名'东方美人'。",
    tips: "水温不宜太高，85-90°C为佳。用白瓷盖碗冲泡，可充分欣赏其白、绿、黄、红、褐五色茶叶的美丽外观。",
    color: "#d9843c"
  },
  {
    id: 12,
    name: "Silver Needle",
    nameZh: "白毫银针",
    category: "white",
    origin: "中国福建·福鼎",
    brewTemp: "75-85°C",
    brewTime: "3-5分钟",
    caffeine: "low",
    flavor: ["毫香", "清甜", "鲜爽", "花香"],
    highlights: "白毫银针是白茶中的极品，全部由肥壮的单芽制成，满披白毫如银似雪。制作工艺极简，不炒不揉，自然萎凋干燥，最大程度保留了茶叶的天然物质。汤色浅杏黄，入口清甜鲜爽，有'一年茶三年药七年宝'之说。",
    tips: "建议用较低水温（80°C左右）冲泡，浸泡时间可稍长。老白茶可用煮饮法，风味更加醇厚甘甜。",
    color: "#f0e6a0"
  },
  {
    id: 13,
    name: "White Peony",
    nameZh: "白牡丹",
    category: "white",
    origin: "中国福建·福鼎、政和",
    brewTemp: "80-90°C",
    brewTime: "3-5分钟",
    caffeine: "low",
    flavor: ["花香", "毫香", "清甜", "醇和"],
    highlights: "白牡丹取一芽一二叶制成，因冲泡后绿叶衬托银白芽心，宛如牡丹花初放而得名。兼具银针的鲜爽与寿眉的醇厚，被视为白茶中性价比最高的品类。新茶花香清雅，陈茶则药香渐显，别有风味。",
    tips: "盖碗冲泡最能体现其花香与毫香的层次感。存放三年以上的白牡丹可尝试煮饮，口感更加温润绵柔。",
    color: "#edd98a"
  },
  {
    id: 14,
    name: "Sheng Puer (Raw)",
    nameZh: "生普洱",
    category: "puer",
    origin: "中国云南·西双版纳、临沧",
    brewTemp: "95-100°C",
    brewTime: "1-3分钟",
    caffeine: "high",
    flavor: ["山野气韵", "苦甘交织", "生津", "回甘强烈"],
    highlights: "生普洱由云南大叶种晒青毛茶压制而成，是可以'越陈越香'的活茶。新茶口感强烈、苦涩明显但回甘迅速；随着自然陈化，汤色由黄绿转为金黄琥珀，滋味日趋醇和。名山古树茶更是收藏投资的热门之选。",
    tips: "沸水冲泡，前几泡快速出汤（5-10秒），后续逐渐延长。新茶可适当醒茶，老茶建议用紫砂壶以激发陈韵。",
    color: "#c8a84a"
  },
  {
    id: 15,
    name: "Shou Puer (Ripe)",
    nameZh: "熟普洱",
    category: "puer",
    origin: "中国云南·勐海",
    brewTemp: "95-100°C",
    brewTime: "1-2分钟",
    caffeine: "medium",
    flavor: ["陈香", "糯滑", "枣香", "温润"],
    highlights: "熟普洱通过人工渥堆发酵工艺加速陈化，汤色红浓如酒，口感醇厚顺滑。1973年昆明茶厂首创此工艺，使普洱茶无需长年存放即可获得陈年老茶的温润口感。养胃暖身，是冬日品饮的绝佳选择。",
    tips: "沸水冲泡，第一二泡快速洗茶倒掉以去除渥堆味。正式品饮从第三泡开始，可连续冲泡十余次。",
    color: "#8b4513"
  },
  {
    id: 16,
    name: "Matcha",
    nameZh: "抹茶",
    category: "japanese",
    origin: "日本·京都宇治",
    brewTemp: "70-80°C",
    brewTime: "即冲即饮",
    caffeine: "high",
    flavor: ["海苔香", "鲜甜", "浓郁", "奶油感"],
    highlights: "抹茶源于中国宋代点茶法，由日本发扬光大成为茶道核心。遮阴覆盖栽培的茶叶经石磨碾成超细粉末，饮用时将整片茶叶摄入体内，营养价值极高。浓茶（濃茶）厚重如膏，薄茶（薄茶）清爽起泡。",
    tips: "用茶筅（竹制搅拌器）以'M'形快速搅打至表面细腻起泡。水温70-80°C，过高会产生苦涩味。",
    color: "#5a8c3c"
  },
  {
    id: 17,
    name: "Gyokuro",
    nameZh: "玉露",
    category: "japanese",
    origin: "日本·京都宇治、福冈八女",
    brewTemp: "50-60°C",
    brewTime: "2-3分钟",
    caffeine: "high",
    flavor: ["海苔香", "鲜味", "甘甜", "浓醇"],
    highlights: "玉露是日本最高级的绿茶，采摘前20天以上用遮光棚覆盖茶树，使茶氨酸大量积累。其鲜味（Umami）极为突出，被誉为'能喝的味精'。产量稀少，价格昂贵，是日本茶道中招待贵宾的首选。",
    tips: "冲泡温度极低，50-60°C最佳，用量较大。第一泡浸泡2分钟，细品其浓郁鲜甜；后续可逐步提高水温。",
    color: "#6b9e42"
  },
  {
    id: 18,
    name: "Sencha",
    nameZh: "煎茶",
    category: "japanese",
    origin: "日本·静冈",
    brewTemp: "70-80°C",
    brewTime: "1-2分钟",
    caffeine: "medium",
    flavor: ["清新", "草香", "微涩", "甘甜"],
    highlights: "煎茶是日本人日常饮用最多的茶类，占日本茶产量的七成以上。经蒸汽杀青制成，保留了鲜绿色泽和清新草香。品质从日常饮品到高级煎茶差异很大，好的煎茶鲜爽甘甜，是体验日本茶文化的入门之选。",
    tips: "一般用70-80°C水温冲泡60-90秒。日本人习惯将最后一滴茶也倒尽，认为精华尽在最后一滴。",
    color: "#8ab648"
  },
  {
    id: 19,
    name: "Hojicha",
    nameZh: "焙じ茶",
    category: "japanese",
    origin: "日本·京都",
    brewTemp: "90-100°C",
    brewTime: "1-2分钟",
    caffeine: "low",
    flavor: ["焙火香", "坚果香", "温和", "甘醇"],
    highlights: "焙じ茶是将煎茶或番茶经高温烘焙而成，茶叶呈褐色，咖啡因含量极低。1920年代由京都茶商发明，以其温暖的烘烤香气和温和口感深受喜爱。常作为日本料理的餐后茶，老人小孩皆宜饮用。",
    tips: "可用沸水直接冲泡，不苦不涩，非常容易上手。冷泡后风味也很出色，适合夏日冰饮。",
    color: "#a0704a"
  },
  {
    id: 20,
    name: "Genmaicha",
    nameZh: "玄米茶",
    category: "japanese",
    origin: "日本",
    brewTemp: "85-90°C",
    brewTime: "1-2分钟",
    caffeine: "low",
    flavor: ["米香", "爆米花香", "清爽", "温和"],
    highlights: "玄米茶是将炒过的糙米与煎茶混合而成的特色茶饮，部分米粒会在烘炒过程中爆开如小小的爆米花。原本是为了节省茶叶的庶民饮料，如今却因其独特的米香和低咖啡因而广受欢迎，被称为'爆米花茶'。",
    tips: "85-90°C水温冲泡1-2分钟即可。也非常适合制作拿铁——加入热牛奶后米香与奶香完美融合。",
    color: "#c8b84a"
  },
  {
    id: 21,
    name: "Darjeeling",
    nameZh: "大吉岭红茶",
    category: "black",
    origin: "印度·西孟加拉邦大吉岭",
    brewTemp: "85-95°C",
    brewTime: "3-5分钟",
    caffeine: "medium",
    flavor: ["麝香葡萄香", "花果香", "清爽", "细腻"],
    highlights: "大吉岭红茶产于喜马拉雅山麓，海拔2000米以上，被誉为'红茶中的香槟'。春摘（First Flush）茶色浅香高，夏摘（Second Flush）则具有标志性的'麝香葡萄'香气。是世界三大高香红茶之一。",
    tips: "春摘茶水温不宜太高（85-90°C），不加奶清饮最佳；夏摘茶可适当提高水温，也可加少许牛奶调饮。",
    color: "#d4943a"
  },
  {
    id: 22,
    name: "Assam",
    nameZh: "阿萨姆红茶",
    category: "black",
    origin: "印度·阿萨姆邦",
    brewTemp: "90-95°C",
    brewTime: "3-5分钟",
    caffeine: "high",
    flavor: ["麦芽香", "浓强", "醇厚", "微甜"],
    highlights: "阿萨姆是世界最大的红茶产区，位于印度东北部布拉马普特拉河谷。茶汤浓红厚重，带有标志性的麦芽香气，是英式早餐茶和奶茶的主要基底茶。CTC工艺生产的阿萨姆碎茶出汤快，特别适合调制奶茶。",
    tips: "高水温冲泡，配合全脂牛奶和少许糖制作经典英式奶茶，或用印度马萨拉香料煮制Chai。",
    color: "#b0432e"
  },
  {
    id: 23,
    name: "Ceylon",
    nameZh: "锡兰红茶",
    category: "black",
    origin: "斯里兰卡·努瓦勒埃利耶",
    brewTemp: "90-95°C",
    brewTime: "3-5分钟",
    caffeine: "high",
    flavor: ["柑橘香", "清亮", "爽利", "微涩回甘"],
    highlights: "锡兰红茶产于斯里兰卡，因其旧称'锡兰'而得名。高地茶汤色金黄、香气清扬，是世界红茶市场的重要角色。根据海拔不同分为高地茶、中地茶和低地茶，其中乌巴（Uva）高地茶是世界三大高香红茶之一。",
    tips: "95°C热水冲泡3-5分钟，适合清饮也适合加柠檬片制作冰红茶。汤色明亮不浑浊是好锡兰茶的标志。",
    color: "#c4633a"
  },
  {
    id: 24,
    name: "Earl Grey",
    nameZh: "伯爵茶",
    category: "other",
    origin: "英国（以中国/印度红茶为基底）",
    brewTemp: "90-95°C",
    brewTime: "3-5分钟",
    caffeine: "medium",
    flavor: ["佛手柑香", "花香", "柑橘", "清爽"],
    highlights: "伯爵茶以英国首相格雷伯爵命名，是最经典的调配茶之一。以红茶为基底，加入意大利佛手柑精油调香，散发独特的柑橘花香。从维多利亚时代至今一直是英国下午茶的标配，也是全球知名度最高的调配茶。",
    tips: "90-95°C冲泡3-4分钟，可搭配少许牛奶或一片柠檬。也非常适合制作伯爵茶戚风蛋糕等烘焙甜点。",
    color: "#c47a3a"
  },
  {
    id: 25,
    name: "English Breakfast",
    nameZh: "英式早餐茶",
    category: "other",
    origin: "英国（拼配阿萨姆、锡兰、肯尼亚红茶）",
    brewTemp: "95-100°C",
    brewTime: "3-5分钟",
    caffeine: "high",
    flavor: ["浓醇", "麦芽香", "强劲", "饱满"],
    highlights: "英式早餐茶是英国人每天清晨的必备饮品，通常由阿萨姆、锡兰和肯尼亚红茶拼配而成。追求浓强饱满的口感，能与丰盛的英式早餐和牛奶完美搭配。每天消耗量惊人，英国人每年要喝掉约360亿杯茶。",
    tips: "沸水冲泡4-5分钟，加入适量全脂牛奶是最传统的喝法。'先加奶还是先加茶'是英国人永恒的辩题。",
    color: "#a53c28"
  },
  {
    id: 26,
    name: "Rooibos",
    nameZh: "路易波士茶",
    category: "herbal",
    origin: "南非·开普敦塞德堡山区",
    brewTemp: "95-100°C",
    brewTime: "5-7分钟",
    caffeine: "low",
    flavor: ["蜂蜜香", "坚果香", "微甜", "温润"],
    highlights: "路易波士茶并非真正的茶叶，而是南非特有的豆科灌木针叶。完全不含咖啡因，富含抗氧化物质，汤色红润如琥珀。南非原住民饮用已有数百年历史，近年因其健康功效在全球广受追捧，被称为'来自非洲的红宝石'。",
    tips: "可用沸水长时间浸泡而不会苦涩，非常适合晚间饮用。加入蜂蜜和牛奶制作Rooibos拿铁也十分美味。",
    color: "#c45a30"
  },
  {
    id: 27,
    name: "Chamomile",
    nameZh: "洋甘菊茶",
    category: "herbal",
    origin: "埃及、欧洲各地",
    brewTemp: "90-100°C",
    brewTime: "5-10分钟",
    caffeine: "low",
    flavor: ["苹果香", "花香", "甘甜", "舒缓"],
    highlights: "洋甘菊茶是世界上最古老的草本茶之一，古埃及人将其献给太阳神。金黄色的小花冲泡后散发淡淡苹果香（Chamomile一词源于希腊语'大地的苹果'）。以舒缓安眠功效闻名，是全球最受欢迎的睡前茶饮。",
    tips: "沸水冲泡5-10分钟让花朵充分释放有效成分。可加入蜂蜜和柠檬调味，睡前30分钟饮用效果最佳。",
    color: "#e8d464"
  },
  {
    id: 28,
    name: "Jasmine Tea",
    nameZh: "茉莉花茶",
    category: "green",
    origin: "中国福建·福州、广西横县",
    brewTemp: "80-90°C",
    brewTime: "2-3分钟",
    caffeine: "medium",
    flavor: ["茉莉花香", "鲜灵", "清甜", "醇和"],
    highlights: "茉莉花茶是中国北方最受欢迎的茶类，以绿茶为基底经反复窨制吸收茉莉花香而成。好的茉莉花茶需经七次以上窨花，'鲜灵持久、醇厚回甘'是其品质标志。老北京人的'茶'默认就是茉莉花茶，承载着浓浓的市井文化。",
    tips: "85°C左右水温冲泡，盖碗最佳。第一泡花香最为鲜灵浓郁，不宜久泡以免花香散失、汤味变苦。",
    color: "#b8cc5a"
  },
  {
    id: 29,
    name: "Pu-erh Mini Tuo Cha",
    nameZh: "普洱小沱茶",
    category: "puer",
    origin: "中国云南·下关",
    brewTemp: "95-100°C",
    brewTime: "1-2分钟",
    caffeine: "medium",
    flavor: ["陈香", "烟香", "醇厚", "甘滑"],
    highlights: "沱茶是普洱茶的经典紧压形态，形如碗臼，源于云南下关。小沱茶每颗约5克，一颗一泡非常方便。下关沱茶以其独特的'烟香'著称，是普洱茶中辨识度最高的风味之一，老茶客常以'下关味'称之。",
    tips: "沸水冲泡，先用热水浸润沱茶使其散开，洗茶一到两次后正式品饮。耐泡度极高，可冲泡十五次以上。",
    color: "#7a4422"
  },
  {
    id: 30,
    name: "Dong Ding Oolong",
    nameZh: "冻顶乌龙",
    category: "oolong",
    origin: "中国台湾·南投鹿谷",
    brewTemp: "90-95°C",
    brewTime: "2-3分钟",
    caffeine: "medium",
    flavor: ["焙火香", "奶香", "花果香", "甘醇"],
    highlights: "冻顶乌龙是台湾最具代表性的茶叶，产于南投县鹿谷乡冻顶山。半球形紧卷，经中度发酵和焙火制成，兼有绿茶的清香和红茶的醇厚。传统冻顶乌龙带有迷人的焙火奶香，是台湾茶艺馆最常见的待客茶品。",
    tips: "用紫砂壶或盖碗以90-95°C热水冲泡，每泡控制在30-60秒。温壶温杯后冲泡效果更好，可品七八泡。",
    color: "#c49a30"
  }
];

const TEA_CATEGORY_LABELS = {
  green: "绿茶",
  black: "红茶",
  oolong: "乌龙茶",
  white: "白茶",
  puer: "普洱茶",
  herbal: "花草茶",
  japanese: "日本茶",
  other: "调配茶"
};

const TEA_CATEGORY_EMOJI = {
  green: "🍃",
  black: "🫖",
  oolong: "🏔️",
  white: "🤍",
  puer: "🪵",
  herbal: "🌸",
  japanese: "🇯🇵",
  other: "🫖"
};
